### ISSUE TITLE
Message Popups/ and GUI window do not wrap text or resize accordingly

### ISSUE THREAD

**Issue by Scepticalist** [MScholtes/PS2EXE#1]
See attached - more of an inconveniece than anything:

(1) If you get a message on a compiled executable with a lot of text, the popup box doesn't wrap or resize, meaning that in some cases the "OK" box is off screen and cannot be clicked
![exemessagebox](https://user-images.githubusercontent.com/25341089/69635413-391d4580-104c-11ea-9565-78f22ee37aaa.jpg)

(2) The GUI does not resize when a long path is selected

![GUILongPath](https://user-images.githubusercontent.com/25341089/69635424-3fabbd00-104c-11ea-941e-f202002d231b.JPG)

**Comment by MScholtes** [comment]
Hello Scepticalist,

the one with Win-PS2EXE will be easy to fix, the other one not. Have to think about it if there's an reasonable way to work around since it is a "seldom" issue.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello Scepticalist,

the new version 1.0.1 of PS2EXE addresses your issues. For PS2EXE I followed the Windows approach of first selecting 5/8 of the screen as the maximum size of a window. In Win-PS2EXE I just fixed the field size.

Greetings

Markus
