### ISSUE TITLE
No logical space left to create more user strings.

### ISSUE THREAD

**Issue by si458** [MScholtes/PS2EXE#10]
Hi,

i have a script which has an embedded binary file as a base64 string,

it runs fine using .\test.ps1 or 'Run with PowerShell' without any issues

but when i try to compile it, i keep getting **'No logical space left to create more user strings'**

the embedded file is a 5MB file if that helps

Regards

Simon

**Comment by MScholtes** [comment]
Hello Simon,

sorry, there is a hard limit in PS2EXE I can't change:

PS2EXE converts scripts to C# strings. C# is storing its strings UTF16 encoded, so the size of your script will be doubled. Additionally it is converted to a base64 string which leads to a another growth in size of 33 percent. This is the reason why your script size raises to over 16 MByte when compiled. which leads to this error message: A string in C# is limited to a size of 16 MByte!

I can't do anything about it.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response for 2 weeks
