### ISSUE TITLE
Syntax errors on executable, but pure code works

### ISSUE THREAD

**Issue by belamarib** [MScholtes/PS2EXE#100]
Hello there!

I have a python script that runs normally on anaconda, but when I run the .exe file that was generated with PS2EXE it shows syntax errors right in the beggining of the code, when importing libraries:

`from tqdm.auto import tqdm`
The keyword 'from' is not supported in this language version.

Also:
`device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`
Unexpected 'if' token in expression or statement.

I installed the needed dependencies on the powershell script through the following commands:
`Invoke-Expression ".\Miniconda3\Scripts\conda.exe install python=3.8 pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch"`
`Invoke-Expression ".\Miniconda3\Scripts\pip.exe install --no-input tqdm scikit-image opencv-python configargparse lpips imageio-ffmpeg kornia tensorboard"`

I also added `# -*- coding: utf-8 -*-` on the beggining of the code, but it didn't make a difference.

**Comment by MScholtes** [comment]
Hello @belamarib,

can this be a misunderstanding? **PS2EXE** compiles _powershell_ scripts and no _python_ scripts.

Greetings

Markus

**Comment by belamarib** [comment]
Sorry, I didn't explain right!

I compiled a powershell script that installs miniconda and some python libraries and THEN runs a python script.

So it created the executable, but when I run it these errors above appear.

**Comment by MScholtes** [comment]
Hello @belamarib,

I actually do not know what anaconda is (I always thought it was a snake) but my guess is that necessary windows environment variables are missing - maybe because you are installing in the script and the variables are not available in the current shell context of the script.
And _PS2EXE_ creates an independent executable, there is no autoloading of _Powershell_ modules and no execution of _Powershell_ profile scripts.

Greetings

Markus

**Comment by belamarib** [comment]
Hello @MScholtes,

Anaconda is a virtual environment in which you can install specific versions of libraries without the need to install them in your machine path.

I'm debugging the powershell script and I found out that it creates the miniconda environment but it doesn't install the dependencies properly, so my problem has nothing to do with PS2EXE.

Anyway, thanks for the responses!!
