### ISSUE TITLE
I'm hoping to add one feature: a program packager

### ISSUE THREAD

**Issue by iamtornado** [MScholtes/PS2EXE#101]
PS2EXE is a great tool, and I'm hoping to add one feature: a program packager. Because I want to package the folder as a self-extracting exe file, the user can directly double-click this file to start the powershell script

**Comment by MScholtes** [comment]
Hello @iamtornado,

sorry, this is not possible but often asked (you might see here https://github.com/MScholtes/PS2EXE/issues/59 or here https://github.com/MScholtes/PS2EXE/issues/53 or here https://github.com/MScholtes/PS2EXE/issues/52).

PS2EXE is simply a pure compiler, packing files is an issue for a setup program or an archiver.

Greetings

Markus

**Comment by MScholtes** [comment]
No response
