### ISSUE TITLE
-iconfile 

### ISSUE THREAD

**Issue by Axachi** [MScholtes/PS2EXE#102]
Hi great project . I am trying to add an icon to my EXE file. using the -iconfile parameter. But get compilation errors..

VERBOSE: error CS1567: Error generating Win32 resource: Error reading icon 'c:\TEMP\printer-icon13.png' -- The data is invalid

**Comment by cbtboss** [comment]
You will need to use an actual .ico file and not a png.

**Comment by MScholtes** [comment]
Solution was provided.
