### ISSUE TITLE
Options DPIAware gives Script/Wacatac.b!ml virus warning 

### ISSUE THREAD

**Issue by ITBeheer** [MScholtes/PS2EXE#103]
Hola,

I made an exe and when adding the option -DPIAware the executable was flagged by Windows 11 Defender and removed. stating virus Script/Wacatac.b!ml
I have removed the option and the exe is fine for me but still wanted to inform you guys.

**Comment by MScholtes** [comment]
Hello @ITBeheer,

the malware **Wacatac** is very active these days using the **OneNote** security vulnerability. Please double check whether it might be an correct warning.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed due to inactivity
