### ISSUE TITLE
How to prevent script extraction ?

### ISSUE THREAD

**Issue by AlainB612** [MScholtes/PS2EXE#104]
Hello,

The reserved parameter '-extract' allows to extract the PowerShell script from the executable file.

Is there any way to prevent this extraction? Maybe by adding a compile option.

Kind regards.
Alain

**Comment by MScholtes** [comment]
Hello @AlainB612,

I like the idea of free software, so **PS2EXE** itself is free. I am reluctant to make the compilations generated by PS2EXE closed source.

There may be situations where this makes sense. Please remove the lines
```powershell
if (!string.IsNullOrEmpty(extractFN))
{
	System.IO.File.WriteAllText(extractFN, script);
	return 0;
}
```
and the parameter **-extract** will do nothing.

But remember, an experienced cracker can still extract the script from the binary.

Greetings

Markus

**Comment by endo64** [comment]
This could be added a command line argument to PS2EXE.

**Comment by MScholtes** [comment]
Hello @endo64,

as I mentioned above, I am a firm believer in free software, as this benefits the community as opposed to closed software.
Therefore, I do not remove the option to show the underlying script as a matter of principle.

Greetings

Markus

**Comment by MScholtes** [comment]
No further action
