### ISSUE TITLE
Long path prefix not working

### ISSUE THREAD

**Issue by markendr** [MScholtes/PS2EXE#106]
I have been trying to get long paths working as per [ms doc](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation). The following works as expected on pwsh cmd line, or as a PS1 script..

```
Get-ChildItem -LiteralPath '\\?\C:\Windows'
```

If compile this one-liner with `Invoke-PS2EXE` i get the following error..

```
ERROR: Illegal characters in path.
```
Using a process of elimination `?` is the problem, which seems strange since `?` should not be illegal with LiteralPath as far as I understand..

[Issue #92](https://github.com/MScholtes/PS2EXE/issues/92) seems related but I am not clear if there is a workaround I can use, or if it will need a PS2EXE update.

Thanks, Mark

**Comment by MScholtes** [comment]
Hello @markendr,

you have to set the parameter **-longpaths** for **PS2EXE.ps1** to enable long path interpretation.

Greetings

Markus

**Comment by markendr** [comment]
Hi Markus,

Thanks for the quick reply that long paths are supported -- much appreciated!

Cheers
