### ISSUE TITLE
Error CS1034: Compiler limit exceeded: Line cannot exceed 16777214 characters

### ISSUE THREAD

**Issue by FranLegon** [MScholtes/PS2EXE#109]
When $inputFile has more than 16777214 characters, ps2exe fails with error:
_Error CS1034: Compiler limit exceeded: Line cannot exceed 16777214 characters_
This shouldn't be an issue if no individual line exceeds the limit, but ps2exe is failing when no one line exceeds the limit but the total amount of characters does.
I believe this is because ps2exe function, when converting the contents of $inputFile to base64, is passing a single string to the C# compiler. Looking at Module/ps2exe.ps1 I found:
`
$content = Get-Content -LiteralPath $inputFile -Encoding UTF8 -ErrorAction SilentlyContinue
[...]
$scriptInp = [STRING]::Join("`r`n", $content)
$script = [System.Convert]::ToBase64String(([System.Text.Encoding]::UTF8.GetBytes($scriptInp)))`
which is later sent to C# compiler:
`string script = System.Text.Encoding.UTF8.GetString(System.Convert.FromBase64String(@"$($script)"));`
This is where I black out because I'm not good at C#. Is there a way to pass `script` to the compiler in chunks of less than 16777214 characters?

**Comment by MScholtes** [comment]
Hello @FranLegon,

Maybe I will work on this. 

On the other hand, I see no real reason to support scripts larger than 16 MB. There are better ways to deliver binary data of this size than with a Powershell script or PS2EXE, which show poor performance and noticeable behaviour.

A self-extracting archive or a self-built setup program would be a better choice. There are free tools for this.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @FranLegon,

since there was a pull request anyway, I was able to quickly fulfil your request.

ps2exe can handle larger files, whoever needs it. But this also allowed me to remove the obfuscation that was abused by some malicious scripters.

Greetings

Markus

**Comment by FranLegon** [comment]
Hello @MScholtes
That's great to know, thank you very much!
Regarding your previous comment on using other tools for large files, I understand, but it's also great to be able to create executables having only a module as a dependency.
PS2EXE is a great tool, keep it up!

Fran

**Comment by MScholtes** [comment]
Solved
