### ISSUE TITLE
Get-Credential issue

### ISSUE THREAD

**Issue by thenecroscope** [MScholtes/PS2EXE#11]
When using the get-credential command, instead of seeing the usual security box prompt to type in your credentials, another prompt appears prior and requests:

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters 

Once you click on OK, everything is okay. 

Is there anything that can be done to prevent the pop up box?

Many thanks!

**Comment by MScholtes** [comment]
Hello thenecroscope,

this is a bug of PowerShell and not of PS2EXE (Microsoft "forgot" to define a mandatory Parameter to distinguish between parameter sets) and happens in interactive PowerShell too. 

Please use the command
```powershell
Get-Credential -Credential $NULL
```
if you don't want to pass own parameters to Get-Credential.

Greetings

Markus

**Comment by thenecroscope** [comment]
Brilliant, thanks very much Markus :) I will give that a try a bit later on today.
Thanks 👍  🥇

**Comment by MScholtes** [comment]
Closed since no response for 2 weeks
