### ISSUE TITLE
Powershell Core - 7

### ISSUE THREAD

**Issue by WyattLW** [MScholtes/PS2EXE#110]
Hello, i'm trying to make a script that runs with powershell core,
every time i compile it tho the script runs with powershell 5 under it. ($psversiontable returns 5.something)
and obviously some commands are not recognized

Any way to change the behaviour or to make so it uses powershell 7 when available?

i did read about the limitations about compiling with powershell core cause it doesn't have a compiler but if i understood correctly it's a different matter in here (?).

**Comment by MScholtes** [comment]
Hello @WyattLW,

sorry it is the same thing here. 

**PS2EXE** uses the compiler of **.Net Framework 4.x**, which is integrated in **Powershell 5.x** and can only compile **.Net Framework 4.x** executables. **Powershell 5.x** is a **.Net Framework** application.

**Powershell Core** is a **.Net Core** application, you would need a **.Net Core** compiler here but that is not integrated in any **Powershell** version.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed for no further reaction

**Comment by Luke-Williams9** [comment]
If ps2exe is invoked from Powershell 7, is there any reason it can't detect this and the internally run invoke-ps2exe using powershell 5?

**Comment by MScholtes** [comment]
I'm a bit confused. If ps2exe is invoked from Powershell 7, it detect this and tries to run with the Powershell V5 environment.

Greetings

Markus

**Comment by Luke-Williams9** [comment]
> I'm a bit confused. If ps2exe is invoked from Powershell 7, it detect this and tries to run with the Powershell V5 environment.
> 
> Greetings
> 
> Markus

I think I found the problem. If I only install PS2EXE via Powershell V7, it errors out at line 1, char 2:
_& : The term 'Invoke-ps2exe' is not recognized as the name of a cmdlet_

But if I install PS2EXE as admin in powershell V5, then it works properly from the V7 environment.

So it needs to be installed separately, both in V5 and V7 environments.

**Comment by MScholtes** [comment]
Hello @Luke-Williams9,

I made some tests and think the best way is to install the module only in Windows Powershell (this is version 5). I updated the readme for this.

Greetings

Markus
