### ISSUE TITLE
The module may have listeners

### ISSUE THREAD

**Issue by lypacd** [MScholtes/PS2EXE#111]
I scanned the file with the threatbook sandbox and there were some high-risk behaviors, how can this be explained

**Comment by Kleerkastje** [comment]
This is the positives the .exe files created from this script gives. 

![f3cdfd3940e5e3fe9f3d6392f35d257b](https://github.com/MScholtes/PS2EXE/assets/149209555/e09c8098-378b-40da-8e07-0503f9a4cd5a)

**Comment by MScholtes** [comment]
Hello @Kleerkastje,

**PS2EXE** compiles Powershell scripts into an EXE file. This behaviour is of course suspicious and is reported by many virus scanners, as **PS2EXE** is unfortunately also misused for malware.

The origins of **PS2EXE** were in a more peaceful time. My latest change made it easier for virus scanners to detect malicious behaviour of scripts as I no longer want to support malicious scripters. Therefore there are now more finds on **Virustotal**. The best way out is to report the finding as a false alarm (if so) and to certify your compiled script.

Greetings

Markus

**Comment by MScholtes** [comment]
I assume that the issue no longer exists as there is no feedback.
