### ISSUE TITLE
Add special variables to determine if a script is running in ps2exe or not

### ISSUE THREAD

**Issue by steve02081504** [MScholtes/PS2EXE#115]
I want to make some generic scripts for both powershell and ps2exe, so I need some convenient way to determine whether the script is currently running as an exe or in powershell.
Like special global or environment variables!

**Comment by MScholtes** [comment]
Hello @steve02081504,

I would use the variable **$Host**. In **$Host.Name** is the name of the _Powershell_ host, for **PS2EXE** this is "**PSRunspace-Host**".

With an expression like
```powershell
if ($Host.Name -eq "PSRunspace-Host") { Write-Output "PS2EXE" } else { Write-Output "Some other host" }
```
you can distinguish the environments.

Greetings

Markus

**Comment by steve02081504** [comment]
Thanks!
