### ISSUE TITLE
$host.enternestedprompt()

### ISSUE THREAD

**Issue by pascalrip** [MScholtes/PS2EXE#12]
Hi

I'm trying to convert some of my Powershell scripts. They initially remote connect to different servers and load functions to simplify administration tasks for helpdesk. In order to not close the Powershell session and and keep the shell open, while all preloaded functions remain available for administration, I use the method $host.enternestedprompt().

Script conversion seems fine, but the executable Powershell script ignores the enternestedprompt method and closes the shell right away. So far I didn't figure out an alternative for keeping that shell going until its closed manually. Replacing $host.enternestedprompt() e.g. by an Readhost loop will suppress tab completion.

Is there anything that can be done to keep that executable script shell open and interactive?

Thanks
/pascal

**Comment by MScholtes** [comment]
Hello pascalrip,

I'm sorry to say that *EnterNestedPrompt* is simply not implemented and I do not plan to do as this would be very costly.

What I do not understand is why you don't use PowerShell.exe itself for your needs? I see no benefit in using a compiled script as you want an interactive shell.

Greetings

Markus

**Comment by pascalrip** [comment]
Hi Markus

Thanks for your reply.

Currently I do use PowerShell.exe and it's all working fine, but I tried to make it available as a compiled script (only) to some customers. Even though it's somewhat easy to overcome that hurdle to extract the script code, as well as change it.

Regards
/pascal

**Comment by MScholtes** [comment]
Hello Pascal,

I thought about and made some tests. I have to admit I see no (reasonable) way to get your request going. When you compile it's not interactive.

Sorry

Markus

**Comment by pascalrip** [comment]
Hi Markus

Many thanks for considering my request and investigating this for me!

Best regards
/pascal

**Comment by MScholtes** [comment]
Closed since no response for 2 weeks
