### ISSUE TITLE
PS2EXE pathing issue after converting to exe

### ISSUE THREAD

**Issue by MarkPowSh** [MScholtes/PS2EXE#126]
First, thank you for supporting this great module!

I've encountered the issue that seems to be related to pathing after compiling PS script using PS2EXE to exe and running the exe.

**Error received:** 

```
.\compairsoftware.exe : ERROR: Exception calling "GetDirectoryName" with "1" argument(s): "Illegal characters in path."
At line:1 char:1
+ .\compairsoftware.exe
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Exceptio...cters in path.":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: Cannot bind argument to parameter 'Path' because it is null.
ERROR: Cannot bind argument to parameter 'Path' because it is null.
```

"compairsoftware.exe" is the name of the exe created using PS2EXE  

Additional info:
Script works as expected when run via console (confirmed on 2 different systems Win11 & Win7 with WMF 5.1), no issue observed.
Tried running EXE as administrator both via ISE and FileExplorer on 2 systems - issue is present.
Tried using different pathing methods in script and compiling again - issue is present.
Tried compiling same to exe via PowerGUI.3.8.0.129 - _**no issue observed.**_

Last point makes me think that there is an issue during compilation while using PS2EXE.
Let me know if any additional information can be helpful. 

Any input will be highly appreciated!

**Comment by MarkPowSh** [comment]
Hello @MScholtes,

Please see below:
```
$textFilePath = "C:\Users\username\CompairSoftware\TS_Station_Globals.txt"

try {
    $textContent = Get-Content -Path $textFilePath -ErrorAction Stop
} catch {
    Write-Host "Error reading the text document: $_"
    exit 1
}
```
Let me know if it helps

Mark

**Comment by MScholtes** [comment]
Hello @MarkPowSh ,

the code you posted works fine with PS2EXE.

The error you mentioned occurs in the function **GetDirectoryName**(). Can you tell with what parameter or text you call **GetDirectoryName**(). If the parameter is a variable can you tell which content the variable has?

I think it might has to do with _UNICODE_ characters in an _ASCII_ file.

Greetings

Markus

**Comment by MarkPowSh** [comment]
Hello @MScholtes ,

I'm using GetDirectoryName() as a way to construct the path to the txt file located in the folder with the script:
```
$scriptDirectory = [System.IO.Path]::GetDirectoryName($MyInvocation.MyCommand.Definition)
$expectedSoftwareListPath = Join-Path -Path $scriptDirectory -ChildPath "Expected_software_lists\${versionNumber}\expected_software_list.txt"
```
Note: I've also tried to use different ways to construct the path using $PSScriptRoot, $MyInvocation, Get-Location, $PWD.Path with no success after compiling to exe. 

Mark

**Comment by MScholtes** [comment]
Hello @MarkPowSh,

okay, I think I have the reason for this issue now. Since _PS2EXE_ compiles a script to an executable, the result is not a script anymore. Because of this the script related auto variables are not filled anymore or have unexpected values (like **$MyInvocation**). Please use the solution I noted on the readme page to get the path of the generated executable: https://github.com/MScholtes/PS2EXE#script-variables

Greetings

Markus

**Comment by MarkPowSh** [comment]
Hello @MScholtes ,

Thank you very much for your insight and support! I can confirm you were correct and using solution noted on the readme page resolved the issue.

Best regards, 
Mark
