### ISSUE TITLE
ps2exe - Not sure if it is a problem or limitation

### ISSUE THREAD

**Issue by Surreal2Tech** [MScholtes/PS2EXE#128]
Powershell-GUI Winform

Versions being used:
Powershell/ISE 5.1
Powershell 7.4
VSC 1.86.1

Installed the latest available from POSH Gallery:
ModuleType Version    Name                                ExportedCommands                                                       
Script     1.0.13     ps2exe                              {Invoke-PS2EXE, ps2exe, ps2exe.ps1, Win-PS2EXE...}          

I am writing a generic Azure management script for less technical people.  What I have noticed script works flawless with out error in the following POSH/ISE, POSH, and Visual Studio Code.

Now the issue I see,  After compiling with ps2exe using a slurry of different options the only Azure commandlet that functions is Connext-AzAccount, any other Az commandlet hangs and puts the window in to not responding.

Example of commonly used commandlet that hangs:
Get-AzVM -ResourceID <resid> -Name <vmid> -Status | Out-String

Any direction would be greatly appreciated, I have searched and searched but have not found anything by anybody else pertaining to an issue like this.

**Comment by MScholtes** [comment]
Hello @Surreal2Tech,

since I'm online right now, I'll answer directly:

I don't know what's going wrong, but two hints:

- PS2EXE only runs Windows Powershell 5.1, not Powershell Core 7.x
- a program compiled with PS2EXE starts a new Powershell environment internally, which does not inherit anything from the existing environment (no variables, no loaded modules, possibly also no login to Azure)

Greetings

Markus

**Comment by Surreal2Tech** [comment]
Thank you for the prompt reply,

So anything compiled ps2exe will start posh 5.1 shell if I am understanding your reply correctly.  I will ensure that posh 5.1 is default startup for any ps1 file and not 7.4.

Also as I stated, I am able to connect to azure from a compiled script everytime, but can't do anything else after that. examples below.

_Now the issue I see, After compiling with ps2exe using a slurry of different options the only Azure commandlet that functions is Connect-AzAccount, any other Az commandlet hangs and puts the window in to not responding.

Example of commonly used commandlet that hangs:
Get-AzVM -ResourceID (resid) -Name (vmname) -Status | Out-String__

- which does not inherit anything from the existing environment (no variables, no loaded modules, possibly also no login to Azure)

* no variables - any variable set with in the script seems to work fine, I have tried compiling with static and same situation
* no loaded modules - I have add import for modules as well in the script, same issue
* no login to azure - connect-azaccount works every time with or without variables when compiled

Again thank you for any assistance and information.

**Comment by Surreal2Tech** [comment]
Question:

Is there a limit on the .net sdk version that can be used?

Regards,

**Comment by MScholtes** [comment]
Hello @Surreal2Tech,

to avoid misunderstandings. **PS2EXE** starts a new session. I assume that a connection with **Connect-AzAccount** must be made at the beginning of the script with **PS2EXE** and the associated Azure commands are made within the **PS2EXE** script, as an (implicit) **Disconnect-AzAccount** is made at the end of the **PS2EXE** script.

Greetings

Markus

**Comment by Surreal2Tech** [comment]
Thank you for all the information, I have learned it is dircetly related to the Get-AZVM commendlet, as Start-AZVM or Restart-AZVM work flawless.

I will close this out, again thank you.
