### ISSUE TITLE
EXE files only run on single machine

### ISSUE THREAD

**Issue by tlmorriscb** [MScholtes/PS2EXE#13]
The exe file generated from my script has to be re-made for each new computer I want to run it on, is this expected behavior or is there a setting I'm missing that I need to change?

**Comment by MScholtes** [comment]
No, never heard anything like this.

What is happening when you try to run a compiled script on a new computer? (Is new computer newly installed? Do you have the problem with "old" computers too?)

Greetings

Markus

**Comment by tlmorriscb** [comment]
A series of persistent VMs have exhibited this. None of them are newly provisioned/installed, they've all been around for a while. When we run the exe a window briefly flashes and nothing happens. If we take the base .ps1 with no changes and recreate the exe, it will work on the new machine, but again cannot be ported to a new computer.

**Comment by MScholtes** [comment]
Hello Tristan,

there are some possible reasons why compiled scripts cannot be ported to other machines like version of PowerShell or bitness of the operating system.

The best way to find out is to execute the program in a prompt to see the error message that appears.

Other things you should check is whether Applocker, SRP or something similiar is activated or if the programm is tagged as downloaded from internet (see properties of executable in Windows Explorer).

Greetings

Markus

**Comment by MScholtes** [comment]
Closed, as no answer has been received for over 2 weeks
