### ISSUE TITLE
Windows 10 Patch from March 2024 breaks Powershell script

### ISSUE THREAD

**Issue by ELREYS** [MScholtes/PS2EXE#131]
Hi Guys
unfortunally after the last Windows 10 Patch from March 2024, i have problem to run compiled Powershell script on my Laptops interesting just Powershell script that required Execution Policy change inside the script example:

This script works fine on Laptop that are not updated to the last Patch.

I start a debug on the first line, and the error start exactly there.

Im EventViewer you find a ucrtbase.dll error.

`**_Set-ExecutionPolicy -ExecutionPolicy Bypass_**;
#$Variable
$PrintServer = ""

#List connected Printers
$ConnectedPrinter =  Get-printer | Where-Object {$_.Type -eq "Connection"}

#Install all Printer from Server  
#$AllPrinter = Get-Printer -ComputerName $PrintServer -Name
$SelectedPrinter = Get-Printer -ComputerName $("\\"+$PrintServer) |  Select-Object  Name | Out-GridView -Title "Drucker auswählen (Mit Ctrl/Strg Taste ist Mehrauswahl möglich!)" -PassThru

$ConnectionResult = Test-NetConnection -Hops 1 -ComputerName ""
if ($ConnectionResult.Length -gt 0)
{
    $ConnectionResult
}
foreach ($np in $SelectedPrinter)
{
    $np.Name
    Add-Printer -ConnectionName $("\\"+$PrintServer+"\"+$np.Name)
    Write-Host -ForegroundColor Green $("Drucker " +$np.Name+" wurde erfolgreich installiert. ")
  
}
Write-Host -ForegroundColor Green "Drucker wurden erfolgreich installiert."

Write-Host -BackgroundColor Black -ForegroundColor Yellow "Bitte Standard-Drucker auswählen."

$SortedPrinter = Get-Printer  | Where-Object {$_.Type -eq "Connection"} | Sort-Object
$SelectedPrinter  = $SortedPrinter | Select-Object ShareName | Out-GridView  -Title "Standard-Drucker auswählen" -PassThru
write-host -ForegroundColor Green  $SelectedPrinter.Name

$DefaultPrinter = Get-CimInstance -ClassName Win32_Printer -Filter ("ShareName="+("'"+($SelectedPrinter.ShareName)+"'"))
$DefaultPrinter
Invoke-CimMethod -InputObject $DefaultPrinter -MethodName SetDefaultPrinter

Write-Host "Vorgang abgeschlossen"

`
I just collect the last KB  interesting there was also a Malware KB but ist not listed on my Laptop.

KB890830
KB5035845
KB5034763
Intel Corporation Extension
Intel Corporation Display
KB5001716

I hope you have a solution for this or an explanation.

Thanks

Giuseppe

**Comment by ELREYS** [comment]
Hello [MScholtes](https://github.com/MScholtes)
Thank you fro the reply there are my screenshoot with th error message

![microsoft error powershell](https://github.com/MScholtes/PS2EXE/assets/13600248/1cf52ad2-1bf8-4beb-bad9-8dcfeab06f7b)

**Comment by MScholtes** [comment]
Hello @ELREYS,

follow the error message: please run your the programm / your script elevated (as an Administrator), it cannot work as a standard user.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @ELREYS,

please start your script non-compiled directly from _Powershell_ and see if it works. I do not see any influence of _PS2EXE_ to the issue you face.

Greetings

Markus

**Comment by MScholtes** [comment]
I assume that the issue no longer exists as there is no feedback.
