### ISSUE TITLE
Does not support powershell 5.X+

### ISSUE THREAD

**Issue by LinuxDinoGitHub** [MScholtes/PS2EXE#135]
The compiler does not recognise the newly added properties of the $PSStyle.Progress object added in Powershell 7.2, like view and MaxWidth. May I know if there are alternative ways to compile my ps1 program?

**Comment by MScholtes** [comment]
Hello @LinuxDinoGitHub,

**PS2EXE** only supports _Powershell 5.x_ and not _Powershell Core_. There have been so many fundamental changes that this would mean a nearly complete rewrite.

Greetings

Markus

**Comment by LinuxDinoGitHub** [comment]
Thanks!
