### ISSUE TITLE
switch parameters become an empty string in help text

### ISSUE THREAD

**Issue by Cube707** [MScholtes/PS2EXE#139]
## Problem

when using the `[switch]` type for input parameters, they get converted to the empty string in the help text instead of being printed correctly.

## How to reproduce 

use the following powershell script and safe as `foo.ps1:

```pwsh
[CmdletBinding()]
param (
    [switch]$Bar
)
```

running `get-help .\foo.ps1` hows the switch as expected:

```
tinker.ps1 [-Bar] [<CommonParameters>]
```

but running `ps2exe .\foo.ps1 && .\foo.exe -?` leaves a blank there `-Version` should be (note the double space between `foo.exe` and `[<CommonParameters>]`, which meas that the option was detected, but not printed):

```
NAME
    foo.exe

SYNTAX
    foo.exe  [<CommonParameters>]

...
```

## Expected behavior

Using a `[String]` we get the correct behaviour:

```pwsh
[CmdletBinding()]
param (
    [String]$Bar
)
```

now runing `ps2exe .\foo.ps1 && .\foo.exe -?` produced the expected result:

```
NAME
    foo.exe

SYNTAX
    foo.exe [[-Bar] <string>]  [<CommonParameters>]

...
```

**Comment by MScholtes** [comment]
Hello @Cube707,

this is interesting, try this in your Powershell console:

```powershell
function TestSwitch{[CmdletBinding()]Param([SWITCH]$Bar)}
function TestString{[CmdletBinding()]Param([STRING]$Bar)}

Get-Help TestSwitch
Get-Help TestString
```

This omits the _SWITCH_ parameter too. Seems to be an issue with the _**Get-Help**_ commandlet.
As **PS2EXE** generates the system help messages wrapping the compiled powershell script into a function with the name of the executable, it depends on **_Get-Help_**.

Greetings

Markus

**Comment by Cube707** [comment]
interesting, I did see that in the sourcecode and tested it. But I didn't realize that `ps2exe` always uses powershell 5.

As I only tested in PowerShell 7.4.6 and there the behavior is correct.

**Comment by Cube707** [comment]
using the docker-images `mcr.microsoft.com/powershell:6.0.2-nanoserver-1803` and `lts-7.2-nanoserver-1809` I also confirmed that it worked in both of these versions of Powershell`

```
$ docker run --rm mcr.microsoft.com/powershell:lts-7.2-nanoserver-1809 pwsh -C function TestSwitch{[CmdletBinding()]Param([SWITCH]$Bar)}; Get-Help TestSwitch;

NAME
    TestSwitch

SYNTAX
    TestSwitch [-Bar] [<CommonParameters>]

...
```

```
$ docker run --rm mcr.microsoft.com/powershell:6.0.2-nanoserver-1803 pwsh -C function TestSwitch{[CmdletBinding()]Para
m([SWITCH]$Bar)}; Get-Help TestSwitch;

NAME
    TestSwitch

SYNTAX
    TestSwitch [-Bar]  [<CommonParameters>]

...
```
