### ISSUE TITLE
Certificate check

### ISSUE THREAD

**Issue by CohenItsMe** [MScholtes/PS2EXE#141]
Hi,

After I'm running the ps2exe on my scripts the exe is trying to check for certificate to digicert.com.
how can I disable this check?

**Comment by MScholtes** [comment]
Hello @CohenItsMe,

**ps2exe.ps1** and its generated executables do no certificate check nor do they initiate one - please check the script. This might be your **Powershell**, your **.Net Framework**, your script or a virus scanner or another tool on your computer.

Greetimgs

Markus

**Comment by CohenItsMe** [comment]
Hi @MScholtes ,

Thank you for the quick replay.
I'm sure that my script isn't checking any certificates.

The alert about that the PS process is trying to check certificates only happen if i'm running the exe when i'm running the ps1 there isn't alaret.

**Comment by MScholtes** [comment]
Hello @CohenItsMe,

okay. 
Please can you tell me how did you notice the certificate check? How does the problem affect the execution: delay, function...?
Does your computer have the DigiCert root certificates in the certificate store? Is it a check of a certificate chain or a revocation check?
Do you see some .Net events in the application or setup log of your eventlog when starting the compiled executable?
If you have access to the log of the virus scanner, can you check there, too?
How does another computer react when executing there?

Greetings

Markus
