### ISSUE TITLE
Non-Standard Display for ShouldContinue and ShouldProcess

### ISSUE THREAD

**Issue by bmkaiser** [MScholtes/PS2EXE#15]
I have a script that leverages `$PSCmdlet.ShouldContinue()` as part of a user prompt. However, the produced EXE doesn't display the prompt in a standard way. Instead, it shows the help information inline with the options. Is this intentional or is this a bug? Is there a way to modify the behavior?

**Expected Behavior:**
![Capture](https://user-images.githubusercontent.com/5446414/88242498-59dd7f80-cc5b-11ea-9e6e-239218357ce7.PNG)

**Actual Behavior:**
![Capture1](https://user-images.githubusercontent.com/5446414/88242519-69f55f00-cc5b-11ea-930c-72d9f6859e76.PNG)

**Comment by MScholtes** [comment]
Oops, this is an old one.

Was on vacation, I will look for a solution now.

Greetings

Markus

**Comment by MScholtes** [comment]
OK, the new version 1.0.6 of PS2EXE I released today shows the expected behavior.

Greetings

Markus

**Comment by bmkaiser** [comment]
Thank you, @MScholtes! I've tested and this new version resolves this issue
