### ISSUE TITLE
Block/remove Extract capability and pass through parameters to script.

### ISSUE THREAD

**Issue by sheehand** [MScholtes/PS2EXE#16]
Greetings.

These aren't issues but rather questions, but I read the Issues are how you ask questions on GitHub.

I just found your script on TechNet Gallery last week and have to say I'm quite impressed. I'm using it to compile a single PS1 script to an EXE, but I would like to find out if there is a way to deactivate/block/remove the -Extract capability. Normally I think this capability is a good thing, but I have one scenario where the people I'm handing the EXE to I don't want to be able to pull out the script to dissect it.

Also is there a way to pass through command line parameters from the EXE into the script? Things like "-Verbose" or "-ConfigFile C:\Temp\Config.XML" would be very helpful.

**Comment by MScholtes** [comment]
Hello Sheehand,

I am a big fan of free software, so **PS2EXE** itself is free. I am reluctant to make the compilations generated by **PS2EXE** closed source.

There may be situations where this makes sense. Please replace the expression **_s.StartsWith("-extract", StringComparison.InvariantCultureIgnoreCase)_** in **PS2EXE.ps1** with the expression **_false_** then the parameter _**-extract**_ is gone for future compilations.

Greetings

Markus

PS: You can pass parameters to the generated **EXE** like you would do to the PowerShell script. The only restriction is that for all executables all parameters have the type **STRING**, if there is no implicit conversion for your parameter type you have to convert explicitly in your script.

PPS: Please do not put two requests into one issue.

**Comment by sheehand** [comment]
I'm not sure I follow you on on PS2EXE being free in relation to asking how to block easy extraction of the imbedded PS1 file.

The reason for asking for this is some users try to be too smart for their own good and part of the reason for handing them an EXE file in the first place is so they can't shoot themselves in the foot by messing with a script. I see online there are ways to still extract a script from an EXE (even w/o the -Extract parameter) if they really wanted to go that far, I just didn't want to hand them an easy switch to do it.

I will try the script modification of $False, thank you for that help.

As for the two requests, I thought they were related as they were both parameters being passed to the EXE. My apologies for breaking protocol here by lumping them together. I think I follow you on the second part but if not I will spin up a new issue just for that.
