### ISSUE TITLE
Testing web connectivity behaves differently through the EXE than the raw PS1.

### ISSUE THREAD

**Issue by sheehand** [MScholtes/PS2EXE#17]
Greetings,

I'm using the following logic in a script to try and test URL connectivity:
        $WebRequest = [System.Net.WebRequest]::Create($URL)
        $WebRequest.Timeout = 8000
        $Response = $WebRequest.GetResponse()

When that code is run through the normal .PS1 file, everything works as expected. When it is run through the PS1 embedded in the EXE, it fails. There is a PAC file in on the clients running both the PS1 and EXE use to force things through a proxy, so I suspect this might be an impersonation/credential issue where when run the EXE some things are not passed through correctly.

Have you experienced anything like this before?

**Comment by sheehand** [comment]
Also FYI the same issue comes up in with using a basic cmdlet like Invoke-WebRequest like this:
$Response = Invoke-WebRequest -Uri $URL -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64" -TimeoutSec 5 -ErrorAction Stop
The $Error from a Try Catch construct says the "Unable to contact the remote server".

Again if it is run as a normal PS1 everything is fine. I hope maybe this helps a little explaining the issue.

**Comment by sheehand** [comment]
I think it might be McAfee HIPS blocking it. Checking that now.

**Comment by MScholtes** [comment]
Checking for HIPS seems to be a good idea.

Maybe a configuration for encryption, certificates or - as you already said - proxy configuration is missing.

**Comment by sheehand** [comment]
I can see HIPS blocking the EXE in the HIPS log, so I suspect that's the issue. I will go ahead and close this issue since I am 99% sure that's the issue to the point where I have already asked to have the exe "white listed" in HIPS.
