### ISSUE TITLE
Blank popup opens on Get-ADComputer export via ImportExcel module

### ISSUE THREAD

**Issue by rvdwegen** [MScholtes/PS2EXE#18]
Hello Markus,

I am having a small issue where when executing the following function a blank window will pop up with nothing but the executable name in it.

```
Function GetOfficeOU {
    $DaysInactive = [Microsoft.VisualBasic.Interaction]::InputBox('Input time in days', 'Get Office OU', '300')
    $time = (Get-Date).Adddays(-($DaysInactive))
    Get-ADComputer -SearchBase $Settings.OfficeOU -Filter {LastLogonTimeStamp -lt $time} -Properties LastLogonTimeStamp, Enabled |
    select-object Enabled, Name,@{Name="Last Logon Date"; Expression={[DateTime]::FromFileTime($_.lastLogonTimestamp)}} | Export-Excel $FilenameOffice -AutoSize -StartRow 2 -Title "All Office computers inactive since $DaysInactive days" -TableName Results -Show
    $OutputLabel.Text = "File exported to:`r`n$PSScriptRoot\$FilenameOffice"
}
```

![popup](https://user-images.githubusercontent.com/20259120/90116213-7732d480-dd55-11ea-9523-bb21599cb93f.PNG)

If I comment out the pipe to Export-Excel it doesn't show the pop up.
For the life of me I can't figure out why it would be doing that. Any ideas?

Edit: It does successfully get the information from AD and pipes it to the Export-Excel which creates the excel file without issues.

**Comment by MScholtes** [comment]
Hello Roel,

does the window stay or is it a "blinking Windows" that dissappears immediately? Does it disappear when you click in it or press a key? Does Export-Excel wait for a key press when executed as PowerShell script?

Greetings

Markus

**Comment by MScholtes** [comment]
And I forgot: where is Export-Excel from?

**Comment by rvdwegen** [comment]
Hello Markus,

- The window stays
- It does not respond to any mouse clicks or key presses
- Export-Excel does not wait for any key presses when I manually run a similar query in the powershell console
- Export-Excel is part of the ImportExcel module https://github.com/dfinke/ImportExcel

**Comment by MScholtes** [comment]
Hello Roel,

I have an idea in which context there's something going wrong, but I need time for investigation.

I guess as a workaround you can use the line
```powershell
$ProgressPreference = 'SilentlyContinue'
```
before the call and
```powershell
$ProgressPreference = 'Continue'
```
afterwards.

Greetings

Markus

**Comment by rvdwegen** [comment]
Hello Markus,

That does the trick, excellent! If you need any help testing just me know!

**Comment by MScholtes** [comment]
Hello Roel,

I have found the error and the solution to it in PS2EXE. However, since this error only occurs in rare cases (multiple simultaneous progress bars in one pipeline), I am shying away from releasing a new version of PS2EXE for this.

If you can live with the workaround, I would wait with the release until enough changes have accumulated to make it worth the effort.

Greetings

Markus

**Comment by rvdwegen** [comment]
Hello Markus,

I can absolutely live with it. This is an internal tool only a handful of people will be using and I'm likely the only one who will ever see the code

**Comment by MScholtes** [comment]
OK, thank you. I will release the fix when there are enough changes.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello Roel,

since there were other people suffering from the "lost progress bar window" issue I released the new version 1.0.7 of _PS2EXE_ today that solves the issue.

Greetings

Markus

**Comment by rvdwegen** [comment]
Excellent news! I'll test it out next week. Thanks!

**Comment by MScholtes** [comment]
Issue closed because there was no reaction for a long time.
