### ISSUE TITLE
Compiled files being quarantined

### ISSUE THREAD

**Issue by wtkidd1972** [MScholtes/PS2EXE#22]
I have used your PS2EXE in the past and never had an issue. Over the weekend I imported your PowerShell module version of PS2EXE. Every time I attempt to compile a .ps1 file now, my Bitdefender antivirus software is quarantining the compiled file and indicates it is infected with Gen:Variant.Razy.741658. I have tried multiple .ps1 files, I have tried using Windows PowerShell 5.1 and PowerShell 7, and they all yield the same result. I also restored one of the quarantined files and upload it to https://www.virustotal.com/gui/ and 15/67 engines flagged the .exe as being a threat. Not sure if anyone else is seeing this behavior, but wanted to inform you of it.

**Comment by MScholtes** [comment]
Hello William,

it is the fate of programs generated with PS2EXE that they are sometimes identified as malware. Finally, compiled PowerShell scripts are executed, which is admittedly suspicious. The only hope is to report this to the producer of the antivirus software with the request for correction.

I have created a short program with PS2EXE, but I could not reproduce your result. My program was only detected by 2 of 65 Scanners of VirusTotel. Bitdefender was not included.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello William,

I tested some compiled PowerShell scripts against VirusTotal and noticed, that Bitdefender treats compiled scripts always as virus if they are generated with the switch "-NoConsole". I generated a sample and sent it to Bitdefender with their false positive form.

I Hope they will correct this.

Greetings

Markus

**Comment by wtkidd1972** [comment]
I tested compiling the same scripts yesterday and it worked fine. I'm assuming that Bitdefender engineers have recognized the infection reports and made a correction. After a few days of receiving updates, it is no longer treating compiled scripts as threats.

Thank you,

William T. Kidd
Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by wtkidd1972** [comment]
Thanks for looking into this issue!
