### ISSUE TITLE
Compiling any script is detected as virus

### ISSUE THREAD

**Issue by fd1911** [MScholtes/PS2EXE#23]
Hello there!
I've been using the old software, as well this new repo on github.
The older version, (the TechNet version) after converting a script to an exe a lot of antivirus softares detected them with malware.
On this new repo, after converting a ps1 to exe it's detected once again but with another vulneravility.
This link is a report from a sample ps1 converted and then scanned on [virustotal](https://www.virustotal.com/gui/file/a529a8fe7279a89eaa207055c7e927d6adf4c338d58cc41b200ce52c3287e8b8/community)

Anyway, PS2EXE it's an amazing software and thanks a lot for maintaining it!

**Comment by MScholtes** [comment]
Hello fd1911,

I sent samples to AVG/Avast and Bitdefender to check it as a false positive. Bitdefender corrected its Virus scan engine, and I've got a message from Avast they will correct this in the next signature update.

Greetings

Markus

**Comment by mmillar-bolis** [comment]
VirusTotal came back with only three false positives from Avast, AVG, and SecureAge. I went ahead and submitted false positive reports for all three.

**Comment by MScholtes** [comment]
Thank you very much for this

Markus

**Comment by mmillar-bolis** [comment]
Hey, no problem at all! I have been an avid user of your tool for some years now and am happy to help! I used to use something similar by Fatih Kodak, but his site went offline a few years ago, and I liked what you were doing at the time with the script so now I have a bunch of projects (mostly unpublished) that use your awesome module. Thanks a bunch!

So the same three, Avast, AVG, and SecureAge, are still reporting false positives, so no change yet. I filed new reports with new files just to keep things fresh.

**Comment by MScholtes** [comment]
Thanks again

Markus

**Comment by stampycode** [comment]
FWIW, I tested buying a 12-month 'code signing certificate' from Sectigo for under $90, which made about 90% of the virus detections evaporate. The remaining one still hitting wasn't a commercial desktop AV solution, AFAIK.

I appreciate this might not be an affordable solution for many devs for side projects, but it is something that everyone should be aware of as an option., so I hope this comment at least hopes someone who reads this thread.

**Comment by MScholtes** [comment]
Closed since no response for over 2 weeks

**Comment by javadbacker** [comment]
> FWIW, I tested buying a 12-month 'code signing certificate' from Sectigo for under $90, which made about 90% of the virus detections evaporate. The remaining one still hitting wasn't a commercial desktop AV solution, AFAIK.
> 
> I appreciate this might not be an affordable solution for many devs for side projects, but it is something that everyone should be aware of as an option., so I hope this comment at least hopes someone who reads this thread.

@stampycode could you please explain the steps on how the code signing with Sectigo is done with PS2EXE.

**Comment by MScholtes** [comment]
@javadbacker: You can use signtool.exe that comes with Visual Studio.
For example, _**signtool sign /f MyCertificate.pfx MyProgram.exe**_ might do the job.

For more information see here: https://docs.microsoft.com/de-de/windows/win32/seccrypto/using-signtool-to-sign-a-file

Greetings

Markus
