### ISSUE TITLE
Start-Transcript problem

### ISSUE THREAD

**Issue by darootler** [MScholtes/PS2EXE#25]
Hi!

I've already read your comments [here]( https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5/view/Discussions)

The problem is that i am using a script with about 4 thousand lines of code and a GUI behind. I am using Start-Transcript to log any unexpected output or errors. Is there a way to capture those outputs with the parameters -noOutput and -noErrors set?

Regards
Richard

**Comment by MScholtes** [comment]
Hello Richard,

I'm sorry but I see no option to simulate the Start-TransScript commandlet. You might compile your script without -noConsole, -noError and -noOutput and redirect all output. But this would mean you have a console window in the background and have to control how your programm is invoked, i.e.
YourProgram.exe > Output.log 2> Error.log

Greetings

Markus

**Comment by darootler** [comment]
Hi Markus,

thank you for your answer. Unfortunately this is not an option for me because i am running a GUI. I don't know if that helps but i am using this [tool](https://www.f2ko.de/programme/ps1-to-exe/) now and that fits my needs. But this also spawns a powershell.exe process.

Regards
Richard

**Comment by MScholtes** [comment]
Hello Richard,

it's fine that "Ps1 To Exe" works for you. I know this tool, it has a completely different approach for compiling.

Greetings

Markus

**Comment by MScholtes** [comment]
Issue closed because there was no reaction for over two weeks.
