### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by paxanon** [MScholtes/PS2EXE#27]
Any chance for a feature request, a dash encoding or something, where you can force an encoding to UTF8, default, Unicode or Ascii.

I work on quite a few different computers, with different setups and most of the time i know i want it to have UTF-8 encoding, so it will show non-english characters correct.
i know, "get-content <file> | Set-content -Encoding UTF8 <file-out>", but i have forgotten enough times to think that others might have same issue.

**Comment by MScholtes** [comment]
Hello Danny,

I do not really understand your request. PS2EXE expects UTF8 encoding, but interprets UNICODE files fine if there is a BOM. Ascii files are okay too but obviously then the current charcter set is used.

Greetings

Markus

**Comment by MScholtes** [comment]
Issue closed because there was no reaction for over three weeks.
