### ISSUE TITLE
System Tray Application

### ISSUE THREAD

**Issue by vqjanderson** [MScholtes/PS2EXE#3]
I have a powershell script that runs as an application in the system tray. It is based on the code found here https://bytecookie.wordpress.com/2011/12/28/gui-creation-with-powershell-part-2-the-notify-icon-or-how-to-make-your-own-hdd-health-monitor/. When the application is converted to an exe with no console checked, a blank windows form is created with a taskbar icon. The desired behavior would be to only place the application in the system tray.

**Comment by MScholtes** [comment]
Hello vqjanderson,

I made a shortened version of the script you mentioned. It works fine for me as script and compiled as executable with PS2EXE - independent of compiled with or without console.

What additional functionality is in your script. Can you try to compile the original script and find the difference to yours?

Greetings

Markus

**Comment by vqjanderson** [comment]
I was able to find the issue. I had  $objForm.ShowInTaskbar = $true in my script for some reason. This was causing the task bar form. Thanks for your time, sorry for bothering you with this non issue.

**Comment by MScholtes** [comment]
OK, I wish you a good time.
