### ISSUE TITLE
[enhancement] PowerShell host

### ISSUE THREAD

**Issue by scriptingstudio** [MScholtes/PS2EXE#31]
Is it possible that the compiler would create powershell 7 host to run script? Or better introduce `-version 5|7|auto` parameter or something like that. `Auto` argument would select the latest PS version.

**Comment by MScholtes** [comment]
Hello Matthew,

I'm sorry to say that this is not possible. _Powershell Core_ and _.Net Core_ does not include a compiler so there is nothing **PS2EXE** could use to compile to an executable. The compiler has to be installed manually with the _.Net SDK_ and behaves completely different to the compiler of the _Windows .Net Framework_.

Greetings

Markus

**Comment by scriptingstudio** [comment]
pity, it would be great having possibility to select ps host
