### ISSUE TITLE
[Question-enhancement] Splash screen

### ISSUE THREAD

**Issue by scriptingstudio** [MScholtes/PS2EXE#32]
Hello,

Is it technically possible to implement a splash screen for GUI apps which is working before PS host initialized and PS script loaded?

**Comment by MScholtes** [comment]
Hello Matthew,

without checking, I think it would be possible to realise this. But I don't see the point of doing this, because why isn't the splash screen generated by the powershell script? This would be a better place for it.

Greetings

Markus

**Comment by scriptingstudio** [comment]
Because starting PS host and loading the script may take relatively long time. And the splash should come before that.

**Comment by scriptingstudio** [comment]
Correct me if I am wrong. PS script is packed in EXE, I could not see open text. So unpacking takes time too.

**Comment by MScholtes** [comment]
Hello Matthew,

I can't see how starting a compiled script would take so long that it would be worth displaying a splash screen. How big is your script?

Greetings

Markus

**Comment by scriptingstudio** [comment]
My scripts are usually of 500-1500 lines, including comments, plus I embed libraries like EPPLUS. Before compilation I remove all non-code lines. Result EXE is 300-500 KB. Loading takes 3-6 sec. It seems to me long. Or am I too picky?

**Comment by MScholtes** [comment]
Hello Matthew,

I can't recreate your problem unfortunately, when I start a comparably sized script I get an output immediately. What happens if you don't load the libraries or insert a **Write-Output** command before loading the librairies?

Greetings

Markus

**Comment by scriptingstudio** [comment]
Hello Markus,

Thanks for an idea to profile a loading.

I did tests to measure loading times.
PS host start takes a sec or so. GUI initialization takes less than a sec. So total time is at most 2-3 secs.

You were right, splash screen is overkill.
