### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by jiska78** [MScholtes/PS2EXE#33]
This script is bloody awesome - thank you for taking the time out to write and publish.

A suggestion - it would be great to be able to specify a minimum version of Powershell required to run the script.

IE. Min v5.1 - if doesn't meet requirements tell user they must upgrade to version XXX to run.

**Comment by MScholtes** [comment]
Hello jiska78,

I'm sorry I have to admit I do not understand the question. PS2EXE runs on all supported Powershell versions. The module based version required PowerShellGet, so it needs .Net 4.x and Powershell V4 as minimum. The script based version can compile Powershell V2 and V3 too.

Greetings

Markus

**Comment by jiska78** [comment]
Thanks but I use a lot of commands in my script that will only work on Powershell 5.

I suppose I can get the script to check the powershell version and error out instead.

Regards,

Stuart James
(Sent from phone)


On 5 Jan 2021, at 19:59, MScholtes <notifications@github.com> wrote:

﻿

Hello jiska78,

I'm sorry I have to admit I do not understand the question. PS2EXE runs on all supported Powershell versions. The module based version required PowerShellGet, so it needs .Net 4.x and Powershell V4 as minimum. The script based version can compile Powershell V2 and V3 too.

Greetings

Markus

**Comment by MScholtes** [comment]
I think it would be best to check in script. If you need an exact Powershell version test for version 5.x, you could use code like this
```powershell
if ($PSVersionTable.PSVersion.Major -ne 5) 
{ Write-Output "Not supported Powershell version"
  exit }
```

Greetings

Markus

**Comment by jiska78** [comment]
Perfect, thanks.

Regards,

Stuart James

**Comment by MScholtes** [comment]
Closed due to no response for several weeks
