### ISSUE TITLE
create directory

### ISSUE THREAD

**Issue by princdoberman** [MScholtes/PS2EXE#35]
Dear Markus, nice work.
But I have one problem.
When I try to create directory ...

[System.IO.Directory]::CreateDirectory($PathMyFolder) ...

I got error...  Exception calling "CreateDirectory" with "1" argument(s): "Path cannot be the empty string or all whitespace."

Is it possible to make that work to create new folder in folder where is *.exe.
From ps1 script work without problem.

**Comment by MScholtes** [comment]
Hello princdoberman,

according to the exception message this is no issue with _PSEXE_, **_$PathMyFolder_** seems to be empty.

Perhaps you have stumbled across the topic of script variables? Then see the remarks to this on the readme page of this repository.

Greetings

Markus

**Comment by princdoberman** [comment]
As I said earlier ...
ps1 script is executed without error from PowerShell.

But when I compile in .exe ...  got error "Path cannot be empty string ..."
It looks like .exe can't retrieve path.

**Comment by princdoberman** [comment]
you can try put that at test.ps1 and compile to .exe:

$MyTime = $(((get-date).ToLocalTime()).ToString("yyyyMMddT_HHmmssZ"))
$MyFolder = $env:COMPUTERNAME
$PathMyFolder = Join-Path $PSScriptRoot $MojFolder
[System.IO.Directory]::CreateDirectory($PathMyFolder)
$txtName = "$MyTime.txt"
$txtbase = Join-Path $PathMyFolder $txtName

Get-WmiObject -Class Win32_ComputerSystem | out-file $txtbase -Encoding utf8 -Append

**Comment by MScholtes** [comment]
Would you please read my answer. The issue and the solution is explained there!

**Comment by princdoberman** [comment]
I apologize, but I don't understand.
Maybe I don't know the PowerShell enough or don't understanding the language since English is not my native language.
From your answer I can't find any tip/clue to solution.
You think I've got something wrong with the variables? ( everything with variables work in native ps1 script ) 
On which remark of this repository you think ?

**Comment by MScholtes** [comment]
OK:
You are using the variable **$PSScriptRoot** to get the directory of the script.
When you compile your script to an executable it is no script anymore so this variable is empty.
This leads to your error.

Please look at the readme page of this repository (the web page you get when you go to the repository in your browser). There is a paragraph **Remarks** with a subparagraph **Script variables:**. Here a possible solution is presented.

Greetings

Markus

**Comment by princdoberman** [comment]
Sorry ... I find on tab Wiki...
Remarks ...
Script variables .... Especially the variable $PSScriptRoot is empty.

Thanks.
