### ISSUE TITLE
Solve AV

### ISSUE THREAD

**Issue by int3ring0** [MScholtes/PS2EXE#37]
Hello,
in our company we use a so called next gen AV solution. It detects suspcious behaivour. And all this  great tool does is suspect to it.
One way to solve the AV problem on our side would be to allow users to sign their executables by your software. Any chance to get a parameter like signig to add a certificate?
Because we have a code signing certificate for our developers and of course this is white listed in the AV
Best wishes
Thorsten

**Comment by MScholtes** [comment]
Hello int3ring0,

there is no .Net or Windows built-in method to do that. You have to use **_signtool.exe_** that comes with _Visual Studio_.
For example, **_signtool sign /f MyCertificate.pfx MyProgram.exe_** might do the job.

For more information see here: https://docs.microsoft.com/de-de/windows/win32/seccrypto/using-signtool-to-sign-a-file

Greetings

Markus

**Comment by MScholtes** [comment]
Closing as there is no reaction from the issuer.
