### ISSUE TITLE
'-' is shown as '?' after compiling to exe

### ISSUE THREAD

**Issue by RichardLeiden** [MScholtes/PS2EXE#39]
![Snap1](https://user-images.githubusercontent.com/79874861/109559219-b3076e80-7ada-11eb-9734-60a2954d4e62.jpg)

**Comment by PenguinPaws** [comment]
Is that string copied & pasted from somewhere?
The dashes (1st vs 2 & 3) look slightly different. Maybe one of them is an emdash or something similar?

**Comment by MScholtes** [comment]
Hello Richard,

this is obviously not an _ASCII dash_ but probably an _em dash_. **_Powershell.exe_** is very patient there, **_PS2EXE_** is not.

Please change the character or encode the source file as UTF8 or UTF16 or use a codepage that supports em dash or select a font that supports this character (or a combination of those actions).

Greetings

Markus

**Comment by RichardLeiden** [comment]
Thanks both for your help.
I didn't notice the difference in the '-'
