### ISSUE TITLE
Folder Path parameter keeps getting rejected with "Wrong format" message

### ISSUE THREAD

**Issue by yportier** [MScholtes/PS2EXE#4]
Hi. Great job on this utility, it's really neat!

I have a mandatory parameter to my script which is a folder path, however I am entering it (quotes, no quotes, backslash escaped or not, ...), it keeps getting rejected.  
Below is how the script parameters are set (it works as intended in PowerShell ISE)

```
Param(
    [Parameter(Mandatory=$True, HelpMessage="Folder")] [System.IO.DirectoryInfo] $path,
    [Parameter(Mandatory=$True, HelpMessage="Log file")] [System.IO.FileInfo] $logFile
)
```

**Comment by MScholtes** [comment]
Hello yportier,

PS2EXE compiles to an executable. Executables have to be accessible from Windows Explorer and from cmd.exe, so no PowerShell or .Net types can be passed as parameter. There is no way that you can pass a value of type [System.IO.DirectoryInfo] or [System.IO.FileInfo] to an executable, executables only "understand" strings.

You have to rework the signature of your script to receive string and convert them later to the desired .Net types.

Greetings

Markus

**Comment by yportier** [comment]
Ok understood. Thanks for this clarification.
