### ISSUE TITLE
Wrong kernel version reported

### ISSUE THREAD

**Issue by rashil2000** [MScholtes/PS2EXE#40]
I don't know how, but PS2EXE is reporting the wrong kernel version for Windows 10. 

Steps to reproduce: 

1. Put the text `"$([System.Environment]::OSVersion.Version)"` in a file called test.ps1 and run it in PowerShell. 
The output (on my machine) is 10.0.19042.0
2. Now run the command `ps2exe test.ps1`. The executable test.exe will be created. Run the executable. 
The output (on my machine) is 6.2.9200.0

**Comment by MScholtes** [comment]
Hello rashil2000,

this is a "feature" of Windows 10 that tells all programms it is Windows 8 for compatibility reasons. You have to compile programs with a special manifest to prevent this.

Compile your script with the additional parameter **_-supportos_** to use this manifest and tell Windows your program is "Windows 10 aware".

Greetings

Markus

**Comment by MScholtes** [comment]
Hello rashil2000,

I do not think you have to worry about compatibility, there is not much happening when using the parameter. 

See this MS docs article: https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1 

Especially: "_Declaring support for Windows 8.1 or Windows 10 in your app manifest will not have any effect when running your app on previous operating systems._"

Greetings

Markus

**Comment by rashil2000** [comment]
Okay, thank you for the help! I'll close this issue.
