### ISSUE TITLE
windows 7 launch issue

### ISSUE THREAD

**Issue by daemon1995** [MScholtes/PS2EXE#42]
Hi, it happens when launch in windows 7, before it requires installed framework 4. After install it i get this when launch any compiled ps1 to exe:
```
   Problem Event Name: APPCRASH
   Application name: test.exe
   App version: 0.0.0.0
   Application time stamp: 6062e820
   Fault Module Name: KERNELBASE.dll
   Fault module version: 6.1.7601.17514
   Error module timestamp: 4ce7c78c
   Exception code: e0434352
   Exception offset: 000000000000a49d
   OS Version: 6.1.7601.2.1.0.256.1
   Language code: 1049
   Additional information 1: 152d
   Additional Information 2: 152d49a18dcb45231bb1c1efff527c4d
   Additional Information 3: 1939
   Additional Information 4: 1939f0e2c35703370b41f4b9742b71a2
```

**Comment by MScholtes** [comment]
Hallo daemon1995,

the error you get results from a missing .Net Framework 4 where you execute the compiled script. .Net 4 is not only required to compile the script, it is also required to run the generated executable.

You may look at the script based version os PS2EXE here [https://github.com/MScholtes/TechNet-Gallery](), it works with .Net 3.5 too.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed as there was no response for over 3 weeks

**Comment by kapils95** [comment]
hello sir,
.Net Framework 4 is installed but same error is display
