### ISSUE TITLE
Localized language characters receiving errors

### ISSUE THREAD

**Issue by ReitanYa** [MScholtes/PS2EXE#44]
I have not tested with other languages, but I suspect the same will happen unless Norwegian is the exception. Seemingly after last release, all Norwegian letters/special characters (ÆØÅ) no functions after being compiled to EXE. I did not experience this issue mid/late march.

I.e. running the script with powershell will output "ÆØÅ", but after compiling to exe it will output "???"

See attached images.
![RunwithPS](https://user-images.githubusercontent.com/21246199/115875648-b87f9600-a445-11eb-84ab-2ea1689d85d9.png)
![RunExe](https://user-images.githubusercontent.com/21246199/115875652-b9182c80-a445-11eb-9c60-ff8a2d775b00.png)

**Comment by MScholtes** [comment]
Hello ReitanYa,

PS2EXE expects source files encoded in UTF8, otherwise it cannot display special characters correctly. UTF16 works fine too. Would you please verify this?

Greetings

Markus

**Comment by ReitanYa** [comment]
After running a few tests I can verify that the issue is not caused by the PS2EXE module itself, but rather PS encoding as you suspected. My issue was solved by not using set-content (using -encoding replacing with piping to out-file. Trying New-Item might also solve the issue if out-file does not.

Thanks Markus, greatly appreciated!

-Magnus
