### ISSUE TITLE
Write-Progress Not working in console apps

### ISSUE THREAD

**Issue by amoreaulemay** [MScholtes/PS2EXE#45]
The Write-Progress does not work in console apps once converted. When using the
```powershell
-noconsole
```
argument it shows a windows forms progress bar, but it should also be working in console apps.

**Comment by MScholtes** [comment]
Hello amoreaulemay,

the commandlet **_Write-Progress_** is not implemented in console mode, as it would be too much work to implement.

I will update the readme page with the information soon, forgot this.

Sorry

Markus

**Comment by scriptingstudio** [comment]
> the commandlet Write-Progress is not implemented in console mode, as it would be too much work to implement.

from cmdlet help:
```
SYNOPSIS
    Displays a progress bar within a PowerShell command window.
```
Is `console mode` not the same as `PowerShell command window`?

**Comment by MScholtes** [comment]
Hello Matthew,

the basic input and output functions I had to rewrite in C# for PS2EXE as I cannot use the functions of Powershell (as there is no Powershell).

Greetings

Markus

________________________________
Von: Matthew Gray ***@***.***>
Gesendet: Dienstag, 4. Mai 2021 10:20
An: MScholtes/PS2EXE ***@***.***>
Cc: MScholtes ***@***.***>; Comment ***@***.***>
Betreff: Re: [MScholtes/PS2EXE] Write-Progress Not working in console apps (#45)


the commandlet Write-Progress is not implemented in console mode, as it would be too much work to implement.

from cmdlet help:

SYNOPSIS
    Displays a progress bar within a PowerShell command window.


Is console mode not the same as PowerShell command window?

**Comment by amoreaulemay** [comment]
I guess I could also implement a DIY progress bar instead of the built in method; that's what I do in my bash scripts anyway, I was just happy there was a built in method in PowerShell.

Thanks for the swift reply!

**Comment by MScholtes** [comment]
Hello amoreaulemay,

I updated the readme page with the information. I hope you can get along with it.

Greetings

Markus

**Comment by amoreaulemay** [comment]
Alright thanks!
