### ISSUE TITLE
ICON option?

### ISSUE THREAD

**Issue by ansred** [MScholtes/PS2EXE#48]
Hi, 

Much respect to this clean compiler tool

Is there away to add software metadata and ICON?

Thanks

**Comment by MScholtes** [comment]
Hello ansred,

did you miss the readme page or the help text?

Parameters for PS2EXE are (amongst others):
_iconFile = icon file name for the compiled executable
title = title information (displayed in details tab of Windows Explorer's properties dialog)
description = description information (not displayed, but embedded in executable)
company = company information (not displayed, but embedded in executable)
product = product information (displayed in details tab of Windows Explorer's properties dialog)
copyright = copyright information (displayed in details tab of Windows Explorer's properties dialog)
trademark = trademark information (displayed in details tab of Windows Explorer's properties dialog)
version = version information (displayed in details tab of Windows Explorer's properties dialog)_

Greetings

Markus

**Comment by ansred** [comment]
I totally missed that line.

 iconFile = icon file name for the compiled executable

Thanks so much!
