### ISSUE TITLE
'x' close dialog option on progress bars

### ISSUE THREAD

**Issue by nmpereira** [MScholtes/PS2EXE#49]
Is there a way to add a close dialog/window button on progressbars?

I have a progress bar that downloads a huge file and takes 5-20 mins. I use the Start-BitsTransfer/Expand-Archive methods that has a built in progressbar on the console. When the progressbar is running and takes longer than I'd like, i can simply close the console window. With PS2E2E, I cannot close the progressbar (even with task manager sometimes).

**Comment by MScholtes** [comment]
Hello nmpereira,

your request is not really clear. When you close a console window with a Powershell script, the script is forcefully stopped. I guess this is not what you want.

If you find the progress bar window disturbing, please set the following automatic Powershell variable before:
```
$ProgressPreference = 'SilentlyContinue'
````
If you want progress bars to reappear, set the variable to its default value _'Continue'_.

Greetings

Markus

**Comment by nmpereira** [comment]
Hello Markus,

My request is specifically to do with 'closing' the progressbar window. I would like to have it show, but would also like the option to close it. 

Currently, there is no way to close the child progressbar window nor the parent gui window (because it wants me to close all child windows before interacting with the parent window). Even if it closes the whole script, to essentially mimic a console window being closed, thats a solid alternative as well.

Right now, the only way to close the script running a progressbar is through task manager, which is not elegant.

**Comment by MScholtes** [comment]
Hello nmpereira,

I will do some research about it, it will take some time for testing.

But PS2EXE programs in NoConsole mode cannot behave like a console program since there is no console.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @nmpereira,

sorry for the late reply. I have done some research, the effort to provide the possibility of closing and also minimising and maximising is very high and is not in any effort to the benefit (I would have to write event handlers for each function, these would also have to be called. The case that a change is to be made to an already closed window must be handled...).

So unfortunately I will not be able to implement the request-.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response
