### ISSUE TITLE
Alternative to `Register-EngineEvent PowerShell.Exiting`

### ISSUE THREAD

**Issue by yportier** [MScholtes/PS2EXE#5]
Sorry for posting an issue here, I can't seem to be able to ask a question on TechNet Gallery.

I have a script that works as a background task (without the need for a GUI) and is meant to be fired up and left running until terminated. When I close the console window it does terminate but not in a clean way as I am basically killing the process but I'm not closing properly some objects (that need to be left open as long as the script is running). I'd like to use an alternative of `Register-EngineEvent PowerShell.Exiting` to execute some cleaning actions when the process gets interrupted. Is there a way to do this ?

**Comment by MScholtes** [comment]
Hello yportier,

what is the reason you don't use Register-EngineEvent PowerShell.Exiting?
Or other question: how can you expect a process to terminate in a clean way when you terminate the process "not in a clean way"?

Greetings

Markus

**Comment by yportier** [comment]
I was under the impression `Powershell.Exiting` doesn't work in the executable version of the script. At least I couldn't make it work as I thought it should.

As for the rest, my script is basically a forever loop waiting for some events to take place. In the executable version (console mode) I do not have any other way of exiting than terminating the console, that means my script gets killed without the chance to exit properly. That's why I was hoping I could intercept the termination of the console and do some cleaning prior and thus exiting in a cleaner way. It's probably a poor design but I'm not advanced enough with PS to do better at the moment.

**Comment by MScholtes** [comment]
Powershell.Exiting does work with PS2EXE, but the problem is that Powershell.Exiting never works when the console window is closed by the X button (this also applies to the "non compiled" version).

I have no idea how to solve your problem but of reworking the design of your application.

**Comment by yportier** [comment]
Ok, that's well understood. I figured out a way to intercept Ctrl-C so I can interrupt my loop and run my cleaning code prior to closing. That's good enough at the moment.
Thanks
