### ISSUE TITLE
Execution in WinPE

### ISSUE THREAD

**Issue by JustBeta** [MScholtes/PS2EXE#50]
What are the prerequisites for being able to run a PowerShell script compiled with PS2EXE in a WinPE environment?

**Comment by MScholtes** [comment]
Hello Justbeta,

the requirements are indentical to Windows Powershell itself: you have to install .Net 4.x and Windows Management Framework 5.1. I guess there are explanations for that on the Internet.

Greetings

Markus

**Comment by JustBeta** [comment]
Thank you for your quick feedback. 

I'll look
