### ISSUE TITLE
[Feature-Request] Add support to run different PS script to uninstall the installed application

### ISSUE THREAD

**Issue by Vijay-Nirmal** [MScholtes/PS2EXE#56]
Add support to run different PS script to uninstall the application with is created using this tool. Also, the uninstaller should be available in Control Panel/Add or Remove programs.

**Comment by MScholtes** [comment]
Hello Vijay-Nirmal,

there seems to be some kind of misunderstanding. The purpose of **PS2EXE** is to pack a Powershell script to an executable and not to install it.

If you want to create an installer for your compiled script, I recommend a tool to create installers like **NSIS** oder **Inno Setup** (even Windows provides one with **IExpress**) for your purposes.

Greetings and sorry

Markus

**Comment by Vijay-Nirmal** [comment]
Sorry, my bad
