### ISSUE TITLE
Cant exit or cancle a while loop with Read-Host

### ISSUE THREAD

**Issue by GabrielShaukan** [MScholtes/PS2EXE#57]
I converted my powershell script that has this line:

while (($PreRelease -ne "Y") -and ($PreRelease -ne "N") -and -not $flagbool)  {
		echo "Enter a valid choice: (Y) or (N)"
		$PreRelease = Read-Host -Prompt 'Is it a pre-Release? (Y) or (N)'
		}

there is no way of closing the executable other than killing it. Is this a bug or is it working as intendded. If so how do i simulate an exiting of a program in the exe ( ctrl + c in powershell).

**Comment by MScholtes** [comment]
Hello Gabriel,

your code is working fine for me. I have no idea what's going wrong.

Greetings

Markus

**Comment by GabrielShaukan** [comment]
You can press cancle or exit the code without inputting anything and it closes?

**Comment by MScholtes** [comment]
Where is the cancel key? I do not have one on my keyboard.

Can it be you compiled your script to an Windows Binary with no console?

Greetings

Markus

**Comment by GabrielShaukan** [comment]
![image](https://user-images.githubusercontent.com/20193958/135416492-2b91f894-1657-4e0d-809c-931b7ca427d6.png)

Thats the cancle button i mean. Clicking x also does not close the program

**Comment by MScholtes** [comment]
Hello Gabriel,

this was a design question, I had to make a decision because console programs behave differently from GUI applications. In Windows GUI programs, the Cancel button or the X button in dialog boxes close the dialog box and not the underlying program, so I implemented it that way.

Greetings

Markus

**Comment by GabrielShaukan** [comment]
Ok thanks i'll just compile it as a console program
