### ISSUE TITLE
Multiple PS in 1 exe

### ISSUE THREAD

**Issue by premium3722** [MScholtes/PS2EXE#59]
Thank you for continuing the project!
Is it possible to convert several PS scripts into 1 exe?
Greetings from Switzerland

**Comment by MScholtes** [comment]
Hello @premium3722,

sorry, no, this is not possible. **PS2EXE** compiles into memory, and there is no way that one script could call another script in memory. This is only possible in file system.

I advice you to use a setup package tool to create an installer (**Microsoft** delivers one in **Windows** with **IExpress**) or use an archiver like **7zip** to generate a self-extracting archive to pack your scripts. You could define a custom run command there that starts your main script.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed, as no feedback
