### ISSUE TITLE
Does not look good with high dpi (4k displays)

### ISSUE THREAD

**Issue by chbwien** [MScholtes/PS2EXE#6]
It looks like the ps2exe creates an highdpi unaware program. So it is scaled and looks therefore not that great. Is there an enhancement for high dpi screens planned?

**Comment by MScholtes** [comment]
Hello chbwien,

you're obviously right. Please give me some time to investigate (it's Corona time and I'm at home working and supporting two little children). And don't expect much, since PS2EXE uses WinForms so the possibilities are limited.

Greetings

Markus

**Comment by chbwien** [comment]
Hi,

this might be a good starting point:
https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

CU

Christian

------ Originalnachricht ------
Von: "MScholtes" <notifications@github.com>
An: "MScholtes/PS2EXE" <PS2EXE@noreply.github.com>
Cc: "chbwien" <beck@fortec.tuwien.ac.at>; "Author" 
<author@noreply.github.com>
Gesendet: 08.04.2020 18:02:57
Betreff: Re: [MScholtes/PS2EXE] Does not look good with high dpi (4k 
displays) (#6)

**Comment by MScholtes** [comment]
Hello Christian,

made some tests with scaling and found that the fonts doesn't look god with other scales but the controls scale fine. Using the advanced WinForm features introduced with Creators Update didn't change anything for me.

I enabled visual styles with the new version 1.0.4 so buttons look better. I do not what more I can do. Do you have a special situation or window where the view is problematic?

Greetings

Markus

**Comment by chbwien** [comment]
Hi,

here a screenshot of one of my programs:

See, the window title is ok, All other text in buttons, list views, edit 
fields, is blurry.

So the main question: Do you provide a manifest for the created exe? The 
default is 'not high dpi aware', so Windows will upscale graphically. If 
you set a manifest, that tells windows, the app is high dpi ready, it's 
up to the program to create a suitable output. .NET is in general 
high-dpi aware, but you have to set this in the created exe... You can 
play with manifests as external file and if you have found the correct 
setting, implement the ressource with the manifest later on...

So this could be a starting point:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v%3Dvs.85)

CU

Christian Beck

------ Originalnachricht ------
Von: "MScholtes" <notifications@github.com>
An: "MScholtes/PS2EXE" <PS2EXE@noreply.github.com>
Cc: "chbwien" <beck@fortec.tuwien.ac.at>; "Author" 
<author@noreply.github.com>
Gesendet: 20.04.2020 18:51:52
Betreff: Re: [MScholtes/PS2EXE] Does not look good with high dpi (4k 
displays) (#6)

**Comment by MScholtes** [comment]
Hello Christian,

sorry, I do not see any screenshot.

Are you talking about your own WinForms windows generated by your PowerShell script or about the windows PS2EXE generates?

Greetings

Markus

**Comment by chbwien** [comment]
Hi!

My own generated windows and elements. There was an inline picture.

How can I send you pictures, so you can see the difference?

Best regards

Christian

------ Originalnachricht ------
Von: "MScholtes" <notifications@github.com>
An: "MScholtes/PS2EXE" <PS2EXE@noreply.github.com>
Cc: "chbwien" <beck@fortec.tuwien.ac.at>; "Author" 
<author@noreply.github.com>
Gesendet: 20.04.2020 20:28:19
Betreff: Re: [MScholtes/PS2EXE] Does not look good with high dpi (4k 
displays) (#6)

**Comment by MScholtes** [comment]
Hello Christian,

ok, I understand now. I thought that you were worried about the look of the PS2EXE generated windows.

I'm not sure if we can get what you want because the high DPI support of WinForms are limited.
- How is the look if you execute your script "not compiled" as a PowerShell script?
- Can you transfer your script to WPF windows? Only WPF delivers a good high DPI look.

Greetings

Markus

**Comment by chbwien** [comment]
Hi,

just run the script within the ps-editor. Some widths are a little bit 
different, but the fonts are good and everything works and looks fine. 
So it is the base process, that needs to be high dpi aware. I believe 
WPF is too complicate for my small GUIs.

Best regards

Christian

------ Originalnachricht ------
Von: "MScholtes" <notifications@github.com>
An: "MScholtes/PS2EXE" <PS2EXE@noreply.github.com>
Cc: "chbwien" <beck@fortec.tuwien.ac.at>; "Author" 
<author@noreply.github.com>
Gesendet: 21.04.2020 12:55:48
Betreff: Re: [MScholtes/PS2EXE] Does not look good with high dpi (4k 
displays) (#6)

**Comment by MScholtes** [comment]
Hello Christian,

I guess you mean the Powershell ISE.

OK, I understand. This could be done with a manifest. I see the problem that this manifest would have to be different for Windows 10, Windows Server 2016, Windows 8.1 and Windows 7.

Maybe you could try this code at the beginning of your powershell script before opening any window:

```powershell
Add-Type -Name WinDPI -Namespace Native -MemberDefinition '
[DllImport("SHCore.dll", SetLastError = true)]
public static extern bool SetProcessDpiAwareness(PROCESS_DPI_AWARENESS awareness);

public enum PROCESS_DPI_AWARENESS
{
    Process_DPI_Unaware = 0,
    Process_System_DPI_Aware = 1,
    Process_Per_Monitor_DPI_Aware = 2
}
'

[Native.WinDPI]::SetProcessDPIAwareness([Native.WinDPI+PROCESS_DPI_AWARENESS]::Process_Per_Monitor_DPI_Aware) | Out-Null
```

If the parameter *Process_Per_Monitor_DPI_Aware* is not what you want you could try *Process_System_DPI_Aware* instead. 
This should work beginning with Windows 8.1 but I do not know what happens in ISE.

Greetings

Markus

**Comment by chbwien** [comment]
Hi,

thank you, this works!

Best regards

Christian

------ Originalnachricht ------
Von: "MScholtes" <notifications@github.com>
An: "MScholtes/PS2EXE" <PS2EXE@noreply.github.com>
Cc: "chbwien" <beck@fortec.tuwien.ac.at>; "Author" 
<author@noreply.github.com>
Gesendet: 22.04.2020 12:49:44
Betreff: Re: [MScholtes/PS2EXE] Does not look good with high dpi (4k 
displays) (#6)

**Comment by MScholtes** [comment]
You're welcome
