### ISSUE TITLE
Option to cancel script execution when closing a Read-Host window via the 'x'-button (see #57)

### ISSUE THREAD

**Issue by FD-IBKuF** [MScholtes/PS2EXE#62]
I understand your decision for implementing the 'cancel' and 'x' button functionality the way you did (see Issue #57). But would it be possible to implement an option or parameter that would change the behavior to cancel the execution of the underlying script?

Otherwise your project is absolutely wonderful and allows me to quickly create small, easy-to-use utilities for our in-house "non-techy" users that would otherwise be intimidated by a console prompt.

**Comment by MScholtes** [comment]
Hello @FD-IBKuF,

I am not really enthusiastic about this idea, as a GUI program then no longer behaves like a GUI program, but I am preparing a switch for the behaviour change.

Greetings

Markus

**Comment by FD-IBKuF** [comment]
I understand your hesitation, and for simple output windows (Write-Host output for example) I would completely agree with you. But x-closing a Input or Choice-Selection Dialog feels like a different situation where a execution halt could be warranted.

**Comment by MScholtes** [comment]
New parameter -exitOnCancel introduced with new version 1.1.11 released today

**Comment by MScholtes** [comment]
Closed for no reaction
