### ISSUE TITLE
Export-CliXml with passwords over 24 characters

### ISSUE THREAD

**Issue by mhokanson** [MScholtes/PS2EXE#64]
When using Get-Credential to create a credential object with a password over 24 characters long, then exporting that credential object via Export-CliXml, the resulting file contains the 25th+ character as the username, rather than the username supplied to Get-Credential.

This only occurs with scripts compiled using PS2EXE, and doesn't occur when the compiled script is run from a ps1 file.

**Comment by mhokanson** [comment]
I've found this only happens when the script is compiled with the -noConsole option enabled.

**Comment by MScholtes** [comment]
Hello @mhokanson,

I was able to recreate the error, I am working on a correction.

Greetings

Markus

**Comment by MScholtes** [comment]
Issue solved with new version 1.1.11 released today

**Comment by mhokanson** [comment]
Thanks!

**Comment by MScholtes** [comment]
Closed since issue solved.
