### ISSUE TITLE
WPF application window size is slightly different from PS1 version

### ISSUE THREAD

**Issue by MeCRO-DEV** [MScholtes/PS2EXE#66]
I'm using PS2EXE to compile my WPF application called BBC:
https://github.com/MeCRO-DEV/BBC

The GUI window is slightly different from the one when running as ps1:

EXE:
![bbc exe](https://user-images.githubusercontent.com/57880343/148632853-400a5297-8329-4676-8012-25986c979f3f.PNG)

PS1:
![bbc ps1](https://user-images.githubusercontent.com/57880343/148632907-c2b29fe5-41e8-47d5-b9c7-448a464e9c64.PNG)

Comparison:
![bbc com](https://user-images.githubusercontent.com/57880343/148632912-85004cb7-9f51-4170-b3b5-dd7578e79530.PNG)

Is there an rendering problem when convered to EXE?

Compiler used:
![Capture](https://user-images.githubusercontent.com/57880343/148633489-62d5d107-6b49-4150-9845-c920b743cb8a.PNG)

I actually tried different option combinations but got the same result.

**Comment by MScholtes** [comment]
Hello @MeCRO-DEV,

**PS2EXE** has no "problem" with _WPF_, it just has nothing to do with it.

I was able to recreate the problem, but I have the same "wrong" window when starting your script with **Powershell ISE**. I think there are some special _WPF_ settings for **Powershell.exe**, but I don't know anything about it. I tried the parameter _-supportos_ with **PS2EXE**, but this didn't help.

Greetings

Markus

**Comment by MeCRO-DEV** [comment]
Hi Markus,

Thank you so much for identifying the issue. I just tried to run the script on ISE and I got the same "weird" window. I guess powershell.exe and the ISE renders the WPF GUI differently? I couldn't believe this as I believe both are using the same WPF engine, which is a part of .net framework.

I will live with it for now.

Cheers,
David

**Comment by MScholtes** [comment]
Hello @MeCRO-DEV,

I am sorry that I did not find the reason for the different appearance. However, since only the title height and the total size of the window are actually affected, I assume that **Windows** causes this difference (these properties are actually provided by the operating system).

Somehow **Windows** thinks this is a different kind of application, perhaps a **Windows XP** application? But I don't know why.

Greetings

Markus

**Comment by MeCRO-DEV** [comment]
Thanks you, Marcus. I'm closing this issue.
