### ISSUE TITLE
Where do I submit? 

### ISSUE THREAD

**Issue by nickarino** [MScholtes/PS2EXE#68]
"the web forms from the virus scanners' vendors for reporting false positives (I've already done it with some of them, please use only the false positive page)!"
Please provide links

**Comment by MScholtes** [comment]
Hello @nickarino,

it depends on the AV engine where to submit false positive samples. Please search on the web site of the vendor of the AV scanner or ask friend Google.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed because there is no reaction
