### ISSUE TITLE
Is it possible to put ps1 in a folder and ps2exe can take everything that is in that same folder and convert it to exe?

### ISSUE THREAD

**Issue by deilsoncso** [MScholtes/PS2EXE#69]
I'm thinking about it to be able to create a utility that removes the sccm client (ccmclean.exe) and then install the sccm client again and for that I would have to put the ccmclean.exe inside the built-in exe, is that possible?

**Comment by MScholtes** [comment]
Hello @deilsoncso,

this is an often asked question, you might see here https://github.com/MScholtes/PS2EXE/issues/59 or here https://github.com/MScholtes/PS2EXE/issues/53 or here https://github.com/MScholtes/PS2EXE/issues/52.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed because there is no reaction
