### ISSUE TITLE
ERROR: Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime

### ISSUE THREAD

**Issue by lelecobh** [MScholtes/PS2EXE#70]
When compiling the Script and executing the .exe file, the following message appears.

ERROR: Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime

**Comment by MScholtes** [comment]
Hello @lelecobh,

you seem to compile on a .Net 3.5 environment and run on a .Net 4 environment.

Please tell me the versions of Powershell, .Net and OS you are using to compile.
Please tell me the versions of Powershell, .Net and OS you are using to execute.
When does the error occur? On compile time or execution time?

Greetings

Markus

**Comment by MScholtes** [comment]
Closed because there is no reaction
