### ISSUE TITLE
McAphee Detects EXE's as Trojan named GenericRXSP

### ISSUE THREAD

**Issue by jlgandy2** [MScholtes/PS2EXE#72]
Anyone else see that McAphee is detecting exe's made with this tool as Trojan named GenericRXSP? All my exe's are getting deleted due to this.

**Comment by drennalls** [comment]
Yes I'm seeing the same thing with a slightly different name (`GenericRX` prefix is common though). Here's what I see in the McAfee event log.
```
 The Trojan named GenericRXTC-EO!<..etc..the suffix changes> was detected and deleted.
```

**Comment by JamesDBartlett3** [comment]
@jlgandy2, @drennalls: [The very first section of this repo's README file](https://github.com/MScholtes/PS2EXE#attention-incorrect-virus-detection) explains this issue, and suggests some actions you can take to help fix it.
