### ISSUE TITLE
The 'Invoke-ps2exe' command was found in the module 'ps2exe'

### ISSUE THREAD

**Issue by hexclann** [MScholtes/PS2EXE#76]
Hello, I installed ps2exe on Windows 11 using `Install-Module ps2exe`. 

Output of  `Get-Modules` :
```
PS C:\Windows\System32> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     1.4.7                 PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider…}
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability…}
Script     1.0.11                ps2exe                              Invoke-ps2exe
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}
```

I get the help screen when I enter just `ps2exe`.    
But when I try to convert a powershell script by `ps2exe -inputFile test.ps1 -x64 -title 'Installer' -company 'Awesome Company' -product 'Installer' -requireAdmin -version '1.1' -copyright 'AwesomeCompany'` I get `The 'Invoke-ps2exe' command was found in the module 'ps2exe'` error. I tried removing the module and adding it again but no luck.

![WindowsTerminal_0vzFmLiS5V](https://user-images.githubusercontent.com/94446515/171337918-a79a150d-716a-4e61-bae7-b44c5948b0b1.png)

Even after running `Import-Module ps2exe` I'm getting the same error.

**Comment by MScholtes** [comment]
Hello @hexclann,

I'n not sure but I guess you are using **Powershell Core**. **_PS2EXE_** requires **Windows Powershell**.

Is this correct? Could you test what happens when you start **_PS2EXE_** in **Windows Powershell**.

Greetings

Markus

**Comment by Marco-ITSM** [comment]
Check your execution policy and see if the module loads with bypass:
`Set-ExecutionPolicy -ExecutionPolicy bypass`

**Comment by ad-xiotz** [comment]
@MScholtes I was using powershell core,  I imported the module on Windows Powershell and everything is working now. Thanks

**Comment by hexclann** [comment]
@MScholtes I was using powershell core, I imported the module on Windows Powershell and everything is working now. Thanks
