### ISSUE TITLE
invocatio error 

### ISSUE THREAD

**Issue by solomoncyj** [MScholtes/PS2EXE#77]
```
> ps2exe "./Slient Better Discord.ps1"
PS2EXE-GUI v0.5.0.27 by Ingo Karstein, reworked and GUI support by Markus Scholtes

& : The term 'Invoke-ps2exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+ &'Invoke-ps2exe'  -inputFile './Slient Better Discord.ps1' -nested
+  ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-ps2exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by MScholtes** [comment]
Hello @solomoncyj,

please see here: https://github.com/MScholtes/PS2EXE/issues/76

Greetings

Markus

**Comment by colegemuth** [comment]
Good day,

I am also running into that same error. The fixes in https://github.com/MScholtes/PS2EXE/issues/76 did not work for me either. I am running in PowerShell 7.

**Comment by mmillar-bolis** [comment]
The fix in that issue is not to use Powershell 7 (which is Powershell Core) but to use Windows' built-in Powershell 5 (which is Windows Powershell). To restate, you cannot use Powershell 7. You must use Powershell 5.

**Comment by MScholtes** [comment]
That is not correct:
- start **Windows Powershell** (maybe administrative if it fits your needs)
- install the module with **install-module ps2exe**
- leave **Windows Powershell**
- start **Powershell Core**
- import the module with **import-module ps2exe -usewindowspowershell**
- you're done

Greetings

Markus
