### ISSUE TITLE
Issue with $PSScriptroot

### ISSUE THREAD

**Issue by bettman406** [MScholtes/PS2EXE#78]
I've noticed that if I try using $PSscriptroot, the compiled exe seems to ignore it. If I run the PS natively, everything works correctly. Once the script is compiled, it doesn't seem to recognize the folder it's being run from.

**Comment by MScholtes** [comment]
Hello @bettman406,

please see the readme page, section **Script variables** under **Remarks**: https://github.com/MScholtes/PS2EXE#script-variables

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no reaction
