### ISSUE TITLE
Task Manager - Background process

### ISSUE THREAD

**Issue by IMBMicroscopy** [MScholtes/PS2EXE#8]
Is it possible to compile the script so that it would appear in the Background processes section of task manager?  I can do this with Sapien power studio

**Comment by MScholtes** [comment]
Hello,

yes. Please compile with the parameter -noConsole. As long as there is no output, the program runs in the background.

Greetings

Markus

**Comment by IMBMicroscopy** [comment]
Thanks, will this work with WPF GUI?
I have multiple run spaces communicating via a synchronised hash table any many of these run spaces have pop up GUI windows, and there’s one window constantly displayed

Sent from my iPad

On 22 Apr 2020, at 8:40 pm, MScholtes <notifications@github.com> wrote:

﻿

Hello,

yes. Please compile with the parameter -noConsole. As long as there is no output, the program runs in the background.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello,

this should work as long as you close your runspaces clean, you can make a test run by starting your script with 
```
powershell.exe -nop "yourscript.ps1"
```
You might want to suppress output by using the additional parameters -noOutput and/or -NoError.

Greetings

Markus

**Comment by IMBMicroscopy** [comment]
Yeah I can’t get it to appear in the background, I’ve turned off all console output etc

thanks
James

Dr James Springfield
Microscopy Facility Manager
Institute for Molecular Bioscience
Level 6 North | 306 Carmody Road (Building 80) | The University of Queensland | Brisbane Qld 4072 Australia
T +61 7 3346 2390 | M +61 423 021 445 | F +61 7 3346 2101 | E microscopes@imb.uq.edu.au<mailto:microscopes@imb.uq.edu.au>
Twitter @IMBmicroscopy

[cid:E1336DB2-0766-4FE0-B720-7E9B5C36318A@imb.uq.edu.au]

Connect: imb.uq.edu.au<http://imb.uq.edu.au> | Subscribe | Facebook | Twitter

This email (including any attached files) is intended solely for the addressee. It may contain private or confidential information. If you are not the intended addressee, you must take no action based on it, nor show a copy to anyone. Kindly notify the sender by reply email. Opinions and information in this email which do not relate to the official business of The University of Queensland shall be understood as neither given nor endorsed by the University. CRICOS Provider Number 00025B.

On 22 Apr 2020, at 10:58 pm, MScholtes <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello,

this should work as long as you close your runspaces clean, you can make a test run by starting your script with

powershell.exe -nop "yourscript.ps1"


You might want to suppress output by using the additional parameters -noOutput and/or -NoError.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello James,

so I need some clearification. In Windows there is nothing like a "background process". A process is in the background when it is not in the foreground.
When you compile your script with PS2EXE and the parameters I adviced you then the process
- will not be shown in the taskbar
- will only appear in the TaskManager list of processes

What do you expect more? Or does it fail to work?

Greetings

Markus

**Comment by IMBMicroscopy** [comment]
So when I compile powershell code using the Sapien power studio suite, the executable is a background process in task manager, ie:
It appears deep down in the background list versus in the “Apps” list at the top of task manager.
Otherwise my code is compiling and running fine with PS2EXE, but I would prefer it to be hidden away from users a bit

PS2EXE code
[cid:802020B5-143B-4784-87FB-C9A5D33363A8@uq.edu.au]


Sapien Powershell code
[cid:CD22867B-E748-4017-ACA2-1A74E59CBF69@modem]

On 23 Apr 2020, at 6:22 pm, MScholtes <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello James,

so I need some clearification. In Windows there is nothing like a "background process". A process is in the background when it is not in the foreground.
When you compile your script with PS2EXE and the parameters I adviced you then the process

  *   will not be shown in the taskbar
  *   will only appear in the TaskManager list of processes

What do you expect more? Or does it fail to work?

Greetings

Markus

**Comment by MScholtes** [comment]
Hello James,

I'm sorry, I can't recreate the behavior.
When I compile and run a test script with PS2EXE and the -noConsole parameter, the running process appears in Task Manager in the list of background processes.

Maybe this helps: [How does Task Manager categorize processes as App, Background Process, or Windows Process?](https://devblogs.microsoft.com/oldnewthing/20171219-00/?p=97606)

Greetings

Markus

**Comment by IMBMicroscopy** [comment]
Hi Markus, thanks for investigating this for me, I’ll take a look at the link

Best James

Sent from my iPad

On 24 Apr 2020, at 6:47 pm, MScholtes <notifications@github.com> wrote:

﻿

Hello James,

I'm sorry, I can't recreate the behavior.
When I compile and run a test script with PS2EXE and the -noConsole parameter, the running process appears in Task Manager in the list of background processes.

Maybe this helps: How does Task Manager categorize processes as App, Background Process, or Windows Process?<https://devblogs.microsoft.com/oldnewthing/20171219-00/?p=97606>

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response for 2 weeks
