### ISSUE TITLE
Is it posible to include dependency-modules in .exe

### ISSUE THREAD

**Issue by etxealaikoion** [MScholtes/PS2EXE#80]
Hello,

I'm "compiling" my powershell scripts using ps2exe, and the programs are running properly. So, first of all, thank you very much. This is more a feature requrest.

In "myScript.ps1", I am using some functions that are placed in an external module file. To do so, I use:
- "Import-Module(".\myLibrary.psm1")"

Then, after compiling my script, I have to carry the ".\myLibrary.psm1" file together with "myScript.exe" in order to the program to work properly.

Is there any way or any workaround to somehow "include" the module inside the program?

Thanks in advance,

Ion

**Comment by MScholtes** [comment]
Hello @etxealaikoion,

sorry, this is not possible but often asked (you might see here https://github.com/MScholtes/PS2EXE/issues/59 or here https://github.com/MScholtes/PS2EXE/issues/53 or here https://github.com/MScholtes/PS2EXE/issues/52).


**PS2EXE** is simply a pure compiler, packing files is an issue for a setup program or an archiver.

Greetings

Markus

**Comment by etxealaikoion** [comment]
Understood.

Thanks for the references Markus :)

**Comment by Slluxx** [comment]
It should be possible to recursively get the module code and insert it into the ps1 script that one wants to creates an exe of, no? This is especially useful if one has a local module. This way, modules don't have to be packaged anywhere. I mean its not much different from other "true" compilers.

**Comment by MScholtes** [comment]
@Slluxx;

sorry, no, this is not possible. **PS2EXE** does not analyse the code but for some conspicuities, so it does not know of any dependencies.

Greetings

Markus

**Comment by Slluxx** [comment]
Im not saying it can right now. I am saying it could if someone codes it into PS2EXE.
So my real questions are: Why is it not implemented? Will it be implemented? And if not, why wont it be implemented?
