### ISSUE TITLE
ERROR: The type [IO.Compression.ZipFile] was not found.

### ISSUE THREAD

**Issue by Tealk** [MScholtes/PS2EXE#81]
Hi,

I am using the following in a script:
`[IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $outpath)`

when I run it as ps script the folder is extracted correctly, but when I convert it to exe I get the following error:
`ERROR: The type [IO.Compression.ZipFile] was not found.`

What can be the reason for this?

**Comment by MScholtes** [comment]
Hello @Tealk,

this error has not much to do with **PS2EXE** except that a **PS2EXE** compiled script starts a new independent **Powershell** session. Therefore you have to execute the command
```powershell
Add-Type -AssemblyName System.IO.Compression.FileSystem
```
in your script before executing an method of **System.IO.Compression**.

Greetings

Markus

**Comment by Tealk** [comment]
Ok thanks that works
i was just confused why it works as .ps1 file but then not as .exe.

Can you tell me why I need this line?
