### ISSUE TITLE
Github Actions Support

### ISSUE THREAD

**Issue by BaTarrY** [MScholtes/PS2EXE#82]
When using normal Powershell your module works as expected.
However, when deploying it on Github Actions using windows-latest, the following error being thrown

```powershell
& : The term 'Invoke-ps2exe' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+ &'Invoke-ps2exe'  -inputFile .\FoxSitesInformation\Get-FoxSitesInform ...
+  ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-ps2exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

![Error Screenshot with code](https://user-images.githubusercontent.com/26472689/183249722-583e129e-87e1-4356-a455-d4e9b75cc330.png)

**Comment by MScholtes** [comment]
Hello @BaTarrY,

**PS2EXE** only runs in _Windows Powershell_, not in _Powershell Core_.

Greetings

Markus

**Comment by BaTarrY** [comment]
Thank you !
I am trying to update shell to “shell: powershell”
will update soon.

**Comment by BaTarrY** [comment]
I wanted to update you, that using “shell: powershell” works as suggested.
apparently 'pwsh' is PowerShell core and 'powershell' is desktop Powershell.

**Comment by neilmcintyre** [comment]
I have the same issue, presume this is still broken.

**Comment by tullius2000** [comment]
Open Windows Powershell by pressing Windows + R and type powershell.

Then use this command: 
Invoke-ps2exe -inputFile "C:\Downloads\file.ps1" -outputfile "C:\Downloads\file.exe"

Result:
PS2EXE-GUI v0.5.0.29 by Ingo Karstein, reworked and GUI support by Markus Scholtes
Reading input file C:\Downloads\file.ps1
Compiling file...
Output file C:\Downloads\file.exe written
