### ISSUE TITLE
Special Character encoding

### ISSUE THREAD

**Issue by tonischranz** [MScholtes/PS2EXE#83]
Somehow special characters like äöüûéè etc. in string literals are not handled correct. See example:
 ````
PS C:\Users\ts22h023\Desktop\uml_test> cat .\uml_test.ps1
$MyStr = "Züpfe, Öpfel und crème brûlée"
Write-Output $MyStr

PS C:\Users\ts22h023\Desktop\uml_test> .\ps2exe.ps1 .\uml_test.ps1
PS2EXE-GUI v0.5.0.27 by Ingo Karstein, reworked and GUI support by Markus Scholtes

You are using PowerShell 4.0 or above.

Reading input file C:\Users\ts22h023\Desktop\uml_test\uml_test.ps1
Compiling file...

Output file C:\Users\ts22h023\Desktop\uml_test\uml_test.exe written

PS C:\Users\ts22h023\Desktop\uml_test> .\ps2exe.ps1 .\uml_test.ps1 .\uml_test_uni.exe -UNICODEEncoding
PS2EXE-GUI v0.5.0.27 by Ingo Karstein, reworked and GUI support by Markus Scholtes

You are using PowerShell 4.0 or above.

Reading input file C:\Users\ts22h023\Desktop\uml_test\uml_test.ps1
Compiling file...

Output file C:\Users\ts22h023\Desktop\uml_test\uml_test_uni.exe written

PS C:\Users\ts22h023\Desktop\uml_test> .\uml_test.exe
Z?pfe, ?pfel und cr?me br?l?e

PS C:\Users\ts22h023\Desktop\uml_test> .\uml_test_uni.exe
Z�pfe, �pfel und cr�me br�l�e

PS C:\Users\ts22h023\Desktop\uml_test> .\uml_test.ps1
Züpfe, Öpfel und crème brûlée
````

**Comment by MScholtes** [comment]
Hello @tonischranz,

there are two main reasons for this:
1. The source file has to be encoded in **UTF8** (or 16 Bit **UNICODE**) to display special characters correctly in compiled form
2. You have no Powershell environment but a runspace that runs the compiled script. You might have to care that your console settings in the runspace are correct to display the special characters. This can be complicated, see this issue https://github.com/MScholtes/PS2EXE/issues/30 (this was a very unfriendly guy, but the issue was very interesting).

Greetings

Markus

**Comment by tonischranz** [comment]
Thank you for your response.
Encoding the source script with UTF-8 did the trick. Thought it was already UTF-8 but wasn't. My bad.

**Comment by tonischranz** [comment]
Hmm seems you can't have both

After saving the script as UTF-8
````
PS C:\Users\ts22h023\Desktop\uml_test> .\uml_test.exe
Züpfe, Öpfel und crème brûlée
PS C:\Users\ts22h023\Desktop\uml_test> .\uml_test_uni.exe
Züpfe, Öpfel und crème brûlée
PS C:\Users\ts22h023\Desktop\uml_test> .\uml_test.ps1                                                                   
ZÃ¼pfe, Ã–pfel und crÃ¨me brÃ»lÃ©e
````
so PowerShell as well as the Windows PowerShell ISE seem not to work with UTF-8, anyway if you know what you want it works the one or the other way

**Comment by MScholtes** [comment]
You have to save as UTF8 with BOM, this is recognized in all combinations.

Greetings

Markus

**Comment by tonischranz** [comment]
Thanks, and sorry for the spam.
