### ISSUE TITLE
Error on long paths after converting with PS2EXE, even with LongPathsEnabled in Registry

### ISSUE THREAD

**Issue by RalphSmorra** [MScholtes/PS2EXE#84]
I have a powershell script which doesn't error on long paths (greater than 260 characters) when running in powershell, but when I convert the script to exe using ps2exe, the executable version of the script errors and can't access long paths: "ERROR: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
   This happens even though LongPathsEnabled set to 1 in the registry, via group policy. I don't see any flags to enable long path support in ps2exe, and it has no manifest file where I could specify support for long paths.
   To reproduce this problem: Make a powershell script that runs Get-ChildItem on folders where the path exceeds 260 characters, then convert it to exe using ps2exe, then run it on a path that is longer, and it will error saying the paths are too long.

**Comment by MScholtes** [comment]
Hello @RalphSmorra,

did you try the parameter _**-longPaths**_?

Greetings

Markus

**Comment by RalphSmorra** [comment]
Thank you! That worked.
