### ISSUE TITLE
Add modules file to the exe file

### ISSUE THREAD

**Issue by CohenItsMe** [MScholtes/PS2EXE#89]
Hi,

this is a sugestion.
I'd like to know if this is even a possible idea to add the module files that i'm useing in my GUI app.
for example let's say that i've created a GUI tool for creating a new VM in VMWARE so i used PowerCLI module.
if someone want to use this app he have to make sure that PowerCLI with the currect version is exising in his OS.
Thank you for this awesome tool.

**Comment by MScholtes** [comment]
Hello @CohenItsMe,

this is no **PSEXE** related question, it's pure **Powershell**. 
You could use something like
```powershell
try {
  Import-Module VMware.PowerCLI -Minimumversion 13.0.0.20829139 -ErrorAction Stop
} catch {
  Write-Error "Missing PowerCLI module!"
}
```
at the beginning of your script.

Greetings

Markus
