### ISSUE TITLE
merge scripts

### ISSUE THREAD

**Issue by IMBMicroscopy** [MScholtes/PS2EXE#9]
Is it possible to merge 20+ scripts into one file to be compiled, so there are no .ps1 dependencies

**Comment by MScholtes** [comment]
Hello,

sorry, no, this is not possible. PS2EXE compiles into memory, and there is no way that one script could call another script in memory. This is only possible in file system.

I advice you to use a setup package tool to create an installer or use an archiver to generate a self-extracting archive to pack your scripts. You could define a custom run command there that starts your main script.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response for 2 weeks
