### ISSUE TITLE
not recognized as an applet of command

### ISSUE THREAD

**Issue by prepstarr** [MScholtes/PS2EXE#94]
PS E:\Personal\Documents\programs> invoke-ps2exe .\powershell-upgrade.ps1
PS2EXE-GUI v0.5.0.28 by Ingo Karstein, reworked and GUI support by Markus Scholtes

& : Le terme «Invoke-ps2exe» n'est pas reconnu comme nom d'applet de commande,
fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du
nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est
correct et réessayez.
Au caractère Ligne:1 : 2
+ &'Invoke-ps2exe'  -inputFile .\powershell-upgrade.ps1 -nested
+  ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-ps2exe:String) [], Comma
   ndNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS E:\Personal\Documents\programs>

**Comment by MScholtes** [comment]
Hello @prepstarr,

PS2EXE cannot run natively on Powershell Core since it contains no compiler. The only way to use it in in compatibility mode.

I described the procedure in a new remark: https://github.com/MScholtes/PS2EXE#remarks

Greetings

Markus
